// Source of the array of books used to create the reading list
var books = [
	// ART
	{ title:"How to Read a Film: Movies, Media, and Beyond", author:"Monaco", year:1977, done:false, genre:"film", wc:197925, 
		ss:"Google Books", sum:"Richard Gilman referred to How to Read a Film as simply \"the best single work of its kind.\" And Janet Maslin in The New York Times Book Review marveled at James Monaco's ability to collect \"an enormous amount of useful information and assemble it in an exhilaratingly simple and systematic way.\" Indeed, since its original publication in 1977, this hugely popular book has become the definitive source on film and media.Now, James Monaco offers a special anniversary edition of his classic work, featuring a new preface and several new sections, including an \"Essential Library: One Hundred Books About Film and Media You Should Read\" and \"One Hundred Films You Should See.\" As in previous editions, Monaco once again looks at film from many vantage points, as both art and craft, sensibility and science, tradition and technology. After examining film's close relation to other narrative media such as the novel, painting, photography, television, and even music, the book discusses the elements necessary to understand how films convey meaning, and, more importantly, how we can best discern all that a film is attempting to communicate. In addition, Monaco stresses the still-evolving digital context of film throughout--one of the new sections looks at the untrustworthy nature of digital images and sound--and his chapter on multimedia brings media criticism into the twenty-first century with a thorough discussion of topics like virtual reality, cyberspace, and the proximity of both to film.With hundreds of illustrative black-and-white film stills and diagrams, How to Read a Film is an indispensable addition to the library of everyone who loves the cinema and wants to understand it better." },
    { title:"The Story of Film: A Worldwide History", author:"Cousins", year:2004, done:false, genre:"film", wc:137708, 
		ss:"", sum:"" },
	{ title:"American Cinema: Directors and Directions", author:"Sarris", year:1968, done:false, genre:"film", wc:105448, 
		ss:"Google Books", sum:"The auteur theory, of which film critic Andrew Sarris was the leading American proponent, holds that artistry in cinema can be largely attributed to film directors, who, while often working against the strictures of studios, producers, and scriptwriters, manage to infuse each film in their oeuvre with their personal style. Sarris's The American Cinema, the bible of auteur studies, is a history of American film in the form of a lively guide to the work of two hundred film directors, from Griffith, Chaplin, and von Sternberg to Mike Nichols, Stanley Kubrick, and Jerry Lewis. In addition, the book includes a chronology of the most important American films, an alphabetical list of over 6000 films with their directors and years of release, and the seminal essays \"Toward a Theory of Film History\" and \"The Auteur Theory Revisited.\" Over twenty-five years after its initial publication, The American Cinema remains perhaps the most influential book ever written on the subject." },
	{ title:"History of the Theater", author:"Brockett and Hildy", year:1968, done:false, genre:"performing", wc:163515, 
		ss:"Google Books", sum:"Known as the \"bible\" of theatre history, Brockett and Hildy's History of the Theatre is the most comprehensive and widely used survey of theatre history in the market." },
	{ title:"Music: A Very Short Introduction", author:"Cook", year:1998, done:true, genre:"performing", wc:40847, 
		ss:"Google Books", sum:"This stimulating Very Short Introduction to music invites us to really think about music and the values and qualities we ascribe to it. The world teems with different kinds of music-traditional, folk, classical, jazz, rock, pop-and each type of music tends to come with its own way of thinking. Drawing on a wealth of accessible examples ranging from Beethoven to Chinese zither music, Nicholas Cook attempts to provide a framework for thinking about all music. By examining the personal, social, and cultural values that music embodies, the book reveals the shortcomings of traditional conceptions of music, and sketches a more inclusive approach emphasizing the role of performers and listeners." },
	{ title:"Everything You’ve Ever Wanted to Know About Classical Music but Were too Afraid to Ask", author:"Henley and Jackson", year:2012, done:false, genre:"performing", wc:0, 
		ss:"Google Books", sum:"The authors have set out to make the world of classical music accessible to all. Three sections steer you through the terminology and etiquestte of classical music, open the fascinating history of the genre and its key figures over the last 1,000 years, and provide a detailed reference guide. From Bach to Brahms, Dubussy to Dvorak, Gershwin to Bernstein - they recommend the best works to listen to and why." },
	{ title:"The Rest is Noise", author:"Ross", year:2007, done:false, genre:"performing", wc:193624, 
		ss:"Google Books", sum:"The scandal over modern music has not died down. While paintings by Pablo Picasso and Jackson Pollock sell for a hundred million dollars or more, shocking musical works from Stravinsky's Rite of Spring onward still send ripples of unease through audiences. At the same time, the influence of modern music can be felt everywhere. Avant-garde sounds populate the soundtracks of Hollywood thrillers. Minimalist music has had a huge effect on rock, pop, and dance music from the Velvet Underground onward. Alex Ross, the brilliant music critic for The New Yorker, shines a bright light on this secret world, and shows how it has pervaded every corner of twentieth century life." },
	{ title:"The Gilded Stage: A Social History of Opera", author:"Snowman", year:2009, done:false, genre:"performing", wc:150271, 
		ss:"Google Books", sum:"The Gilded Stage is a comprehensive tour of the world of opera. From its origins in the courts of northern Italy, to its internationally recognised position in modern culture, Snowman explores the social history of opera houses and impresarios, composers and patrons, artists and audiences." },
	{ title:"A Short Guide to Writing About Art", author:"Barnet", year:1981, done:false, genre:"visual", wc:103295, 
		ss:"Google Books", sum:"A Short Guide to Writing About Art, Eighth Edition, The best-selling text of its kind, equips students to analyze pictures (drawings, paintings, photographs), sculptures and architecture, and prepares them with the tools they need to present their ideas in effective writing." },
	{ title:"Architecture: A World History", author:"Borden, Elzanowski, and Taylor", year:2008, done:false, genre:"visual", wc:137708, 
		ss:"Google Books", sum:"Lavishly illustrated and super-condensed, Architecture: A World History is the perfect gift for any architecture buff. In this pocket-sized book bursting with 600 illustrations, page after page is dedicated to significant architectural movements, time lines that explore the evolution of the practice, and capsule biographies of great architects and examinations of their masterpieces." },
	{ title:"Modern Art 1851-1929: Capitalism and Representation", author:"Brettes", year:1999, done:false, genre:"visual", wc:73148, 
		ss:"Google Books", sum:"Richard R. Brettell's innovative and beautifully-illustrated account, the latest addition to the acclaimed Oxford History of Art series, explores the works of artists such as Monet, Gauguin, Picasso, and Dali--as well as lesser-known figures--in relation to expansion, colonialism, nationalism and internationalism, and the rise of the museum. Beginning with The Great Exhibition of 1851 in London, Brettell follows the development of the major European avant-garde groups: the Realists, Impressionists, Post-Impressionists, Symbolists, Cubists, and Surrealists. Giving attention to the changing social, economic, and political climate, the book focuses on conditions for the development of modern art such as urban capitalism, modernity, and the accessible image made possible by art museums, temporary exhibitions, lithography, and photography. Brettell examines artists' responses to modernism, including changes in representation, vision, and \"the art of seeing.\"" },
	{ title:"Art in Theory 1900-2000", author:"Harrison and Wood", year:1992, done:false, genre:"visual", wc:346318, 
		ss:"", sum:"" },
	// { title:"Brunelleschi’s Dome: How a Renaissance Genius Reinvented Architecture", author:"King", year:2000, done:true, genre:"visual", wc:0, 
	// 	ss:"", sum:""  },
	{ title:"The Judgement of Paris: The Revolutionary Decade that Gave the World Impressionism", author:"King", year:2006, done:false, genre:"visual", wc:124804, 
		ss:"Google Books", sum:"Full of fantastic tidbits of information (such as the use of carrier pigeons and hot-air balloons during the siege of Paris), and a colourful cast of characters that includes Baudelaire, Courbet, and Zola, with walk-on parts for Monet, Renoir, Degas, and Cezanne, The Judgment of Paris casts new light on the birth of Impressionism and takes us to the heart of a time in which the modern French identity was being forged."  },
	
	{ title:"SPQR", author:"Beard", year:2015, done:true, genre:"prehist", wc:163515, 
	// Prehistory
		ss:"", sum:"" },
	{ title:"Greek History: The Basics", author:"Osbourne", year:2004, done:false, genre:"prehist", wc:49500, 
		ss:"", sum:""  },
	{ title:"The Ancient Near East: A Very Short Introduction", author:"Podany", year:2013, done:false, genre:"prehist", wc:35090, 
		ss:"", sum:""  },
	{ title:"The Human Past: World Prehistory and the Development of Human Societies", author:"Scarre", year:2005, done:false, genre:"prehist", wc:192000, 
		ss:"", sum:""  },
	// World history
	{ title:"Europe: A History", author:"Davies", year:1996, done:true, genre:"worldhist", wc:537660, 
		ss:"", sum:""  },
	{ title:"China: A New History", author:"Fairbank", year:1992, done:false, genre:"worldhist", wc:160000, 
		ss:"", sum:""  },
	{ title:"Africans: The History of a Continent", author:"Iliffe", year:1995, done:false, genre:"worldhist", wc:103833, 
		ss:"", sum:""  },
	{ title:"A History of India", author:"Kulke and Rothermund", year:1986, done:false, genre:"worldhist", wc:93500, 
		ss:"", sum:""  },
	{ title:"The Middle East: A Brief History of the Last 2,000 Years", author:"Lewis", year:1995, done:false, genre:"worldhist", wc:135735, 
		ss:"", sum:""  },
	{ title:"1491: New Revelations of the Americas Before Columbus", author:"Mann", year:2005, done:false, genre:"worldhist", wc:141665, 
		ss:"", sum:""  },
	{ title:"A People's History of the United States", author:"Zinn", year:1980, done:true, genre:"worldhist", wc:296960, 
		ss:"", sum:""  },
	// Contemporary History
	{ title:"The Age of Extremes: A History of the World 1914-1991", author:"Hobsbawm", year:1994, done:true, genre:"contemphist", wc:156750, 
		ss:"", sum:""  },
	
	// Classical writings
	{ title:"Oresteia Trilogy", author:"Aeschylus", year:"458 BCE", done:false, genre:"classical", rank:{tgb:114}, wc:40309, 
		ss:"", sum:""  },
	{ title:"Medea", author:"Euripides", year:"431 BCE", done:true, genre:"classical", rank:{tgb:160}, wc:12889, 
		ss:"", sum:""  },
	{ title:"Histories", author:"Herodotus", year:"c. 430 BCE", done:true, genre:"classical", wc:215932, 
		ss:"", sum:""  },
	{ title:"Odyssey", author:"Homer", year:"c. 750 BCE", done:true, genre:"classical", rank:{tgb:9}, wc:149025, 
		ss:"", sum:""  },
	{ title:"Iliad", author:"Homer", year:"c. 750 BCE", done:true, genre:"classical", rank:{tgb:21}, wc:167472, 
		ss:"", sum:""  },
	{ title:"Metamorphoses", author:"Ovid", year:"8 CE", done:false, genre:"classical", rank:{tgb:154}, wc:142009, 
		ss:"", sum:""  },
	// { title:"Enneads", author:"Plotinus", year:"c. 270", done:false, genre:"classical" },
	// { title:"Parallel Lives", author:"Plutarch", year:"c. 100", done:false, genre:"classical" },
	{ title:"The Oedipus Cycle", author:"Sophocles", year:"401 BCE", done:true, genre:"classical", rank:{tgb:51}, wc:74918, 
		ss:"", sum:""  },
	//{ title:"Oedipus at Colonus", author:"Sophocles", year:"401 BCE", done:true, genre:"classical", rank:{tgb:158}, wc:0, 
	//	ss:"", sum:""  },
	//{ title:"Oedipus the King", author:"Sophocles", year:"429 BCE", done:true, genre:"classical", rank:{tgb:51}, wc:0, 
	//	ss:"", sum:""  },
	{ title:"Elektra", author:"Sophocles", year:"c. 400 BCE", done:true, genre:"classical", rank:{tgb:205}, wc:26949, 
		ss:"", sum:""  },
	// { title:"Lives of the Caesars", author:"Suetonius", year:121, done:false, genre:"classical" },
	// { title:"Annals", author:"Tacitus", year:"c. 100", done:false, genre:"classical" },
	{ title:"Epic of Gilgamesh", author:"Unknown", year:"c. 1800 BCE", done:false, genre:"classical", rank:{tgb:136}, wc:35220, 
		ss:"", sum:""  },
	{ title:"Aeneid", author:"Vergil", year:"c. 29-19 BCE", done:false, genre:"classical", rank:{tgb:42}, wc:136635, 
		ss:"", sum:""  },
	{ title:"De Rerum Natura", author:"Lucretius", year:"c. 50 BCE", done:false, genre:"classical", rank:{tgb:227}, wc:88151, 
		ss:"", sum:""  },
	
	// Premodern literature
	{ title:"The Divine Comedy", author:"Alighieri", year:1320, done:true, genre:"premodern", rank:{tgb:11}, wc:207122, 
		ss:"", sum:""  },
	{ title:"Decameron", author:"Boccacio", year:"c. 1350", done:false, genre:"premodern", rank:{tgb:100}, wc:207122, 
		ss:"", sum:""  },
	{ title:"Canterbury Tales", author:"Chaucer", year:1392, done:false, genre:"premodern", rank:{tgb:80}, wc:138837, 
		ss:"", sum:""  },
	{ title:"The Tale of Genji", author:"Shikibu", year:1008, done:false, genre:"premodern", rank:{tgb:128}, wc:96972, 
		ss:"", sum:""  },
	{ title:"One Thousand and One Nights", author:"Various", year:"c. 900", done:false, genre:"premodern", rank:{tgb:28}, wc:600000, 
		ss:"", sum:""  },
	{ title:"The Princess of Cleves", author:"La Fayette", year:1678, done:true, genre:"premodern", rank:{tgb:186}, wc:52863, 
		ss:"", sum:""  },
	
	// Early modern literature
	{ title:"Don Quixote", author:"Cervantes", year:1605, done:true, genre:"early", rank:{tgb:3}, wc:273202, 
		ss:"", sum:""  },
	{ title:"Dangerous Liaisons", author:"Laclos", year:1782, done:true, genre:"early", rank:{tgb:141}, wc:135430, 
		ss:"", sum:""  },
	{ title:"Gargantua and Pantagruel", author:"Rabelais", year:1534, done:false, genre:"early", rank:{tgb:95}, wc:174081, 
		ss:"", sum:""  },
	{ title:"Candide", author:"Voltaire", year:1759, done:true, genre:"early", rank:{tgb:52}, wc:30015, 
		ss:"", sum:""  },
	{ title:"Robinson Crusoe", author:"Defoe", year:1719, done:false, genre:"early", rank:{tgb:103}, wc:91495, 
		ss:"", sum:""  },
	{ title:"Gulliver’s Travels", author:"Swift", year:1726, done:true, genre:"early", rank:{tgb:36}, wc:97730, 
		ss:"", sum:""  },
	{ title:"Tom Jones", author:"Fielding", year:1749, done:true, genre:"early", rank:{tgb:105}, wc:211527, 
		ss:"", sum:""  },
	{ title:"Tristram Shandy", author:"Sterne", year:1759, done:false, genre:"early", rank:{tgb:46}, wc:202441, 
		ss:"", sum:""  },
	
	// 19th Century Literature
	{ title:"Pride and Prejudice", author:"Austen", year:1813, done:true, genre:"19th", rank:{tgb:17}, wc:122189,
		ss:"Google Books", sum:"Austen’s most celebrated novel tells the story of Elizabeth Bennet, a bright, lively young woman with four sisters, and a mother determined to marry them to wealthy men. At a party near the Bennets’ home in the English countryside, Elizabeth meets the wealthy, proud Fitzwilliam Darcy. Elizabeth initially finds Darcy haughty and intolerable, but circumstances continue to unite the pair. Mr. Darcy finds himself captivated by Elizabeth’s wit and candor, while her reservations about his character slowly vanish. The story is as much a social critique as it is a love story, and the prose crackles with Austen’s wry wit.",
		gutenberg:"http://gutenberg.org/ebooks/1342",
		librivox:"https://librivox.org/search/?q=pride%20and%20prejudice&search_form=advanced"},
	{ title:"Emma", author:"Austen", year:1815, done:true, genre:"19th", rank:{tgb:59}, wc:141041, 
		ss:"", sum:"" },
	{ title:"Cousin Bette", author:"Balzac", year:1846, done:true, genre:"19th", rank:{tgb:126}, wc:145446, 
		ss:"", sum:"" },
	{ title:"Eugenie Grandet", author:"Balzac", year:1833, done:true, genre:"19th", rank:{tgb:180}, wc:75400, 
		ss:"", sum:""  },
	{ title:"Father Goriot", author:"Balzac", year:1834, done:false, genre:"19th", rank:{tgb:109}, wc:76000, 
		ss:"", sum:""  },
	{ title:"Lost Illusions", author:"Balzac", year:1837, done:false, genre:"19th", rank:{tgb:162}, wc:157830, 
		ss:"", sum:""  },
	{ title:"Jane Eyre", author:"C. Bronte", year:1847, done:true, genre:"19th", rank:{tgb:41}, wc:86071, 
		ss:"", sum:""  },
	{ title:"Wuthering Heights", author:"E. Bronte", year:1847, done:true, genre:"19th", rank:{tgb:15}, wc:129050, 
		ss:"", sum:""  },
	{ title:"Bleak House", author:"Dickens", year:1852, done:false, genre:"19th", rank:{tgb:116}, wc:200674, 
		ss:"", sum:""  },
	{ title:"David Copperfield", author:"Dickens", year:1850, done:true, genre:"19th", rank:{tgb:45}, wc:157561, 
		ss:"", sum:""  },
	{ title:"Great Expectations", author:"Dickens", year:1860, done:true, genre:"19th", rank:{tgb:27}, wc:111363, 
		ss:"", sum:""  },
	{ title:"The Pickwick Papers", author:"Dickens", year:1836, done:false, genre:"19th", rank:{tgb:190}, wc:184544, 
		ss:"", sum:""  },
	{ title:"A Tale of Two Cities", author:"Dickens", year:1859, done:true, genre:"personal", rank:{tgb:231}, wc:83739, 
		ss:"", sum:""  },
	{ title:"The Brothers Karamazov", author:"Dostoyevsky", year:1880, done:true, genre:"19th", rank:{tgb:13}, wc:208394, 
		ss:"", sum:""  },
	{ title:"Crime and Punishment", author:"Dostoyevsky", year:1866, done:true, genre:"19th", rank:{tgb:14}, wc:155634, 
		ss:"", sum:""  },
	{ title:"The Idiot", author:"Dostoyevsky", year:1869, done:true, genre:"19th", rank:{tgb:54}, wc:180689, 
		ss:"", sum:""  },
	{ title:"The Possessed", author:"Dostoyevsky", year:1871, done:true, genre:"19th", rank:{tgb:69}, wc:211527, 
		ss:"", sum:""  },
	{ title:"The Count of Monte Cristo", author:"Dumas", year:1844, done:true, genre:"19th", rank:{tgb:135}, wc:300000, 
		ss:"", sum:""  },
	{ title:"The Three Musketeers", author:"Dumas", year:1844, done:true, genre:"personal", rank:{tgb:222}, wc:128375, 
		ss:"", sum:""  },
	{ title:"Middlemarch", author:"Eliot", year:1871, done:true, genre:"19th", rank:{tgb:35}, wc:177936, 
		ss:"", sum:""  },
	{ title:"Madame Bovary", author:"Flaubert", year:1856, done:true, genre:"19th", rank:{tgb:10}, wc:98626, 
		ss:"", sum:""  },
	{ title:"A Sentimental Education", author:"Flaubert", year:1869, done:false, genre:"19th", rank:{tgb:87}, wc:119014, 
		ss:"", sum:""  },
	{ title:"Dead Souls", author:"Gogol", year:1842, done:true, genre:"19th", rank:{tgb:75}, wc:130890, 
		ss:"", sum:""  },
	{ title:"Tess of the d’Urbervilles", author:"Hardy", year:1891, done:false, genre:"19th", rank:{tgb:101}, wc:163067, 
		ss:"", sum:""  },
	{ title:"Jude the Obscure", author:"Hardy", year:1895, done:false, genre:"19th", rank:{tgb:194}, wc:85394, 
		ss:"", sum:""  },
	{ title:"The Scarlet Letter", author:"Hawthorne", year:1850, done:true, genre:"19th", rank:{tgb:88}, wc:72000, 
		ss:"", sum:""  },
	{ title:"Les Miserables", author:"Hugo", year:1862, done:false, genre:"19th", rank:{tgb:55}, wc:409770, 
		ss:"", sum:""  },
	{ title:"Moby-Dick; or, The Whale", author:"Melville", year:1851, done:true, genre:"19th", rank:{tgb:6}, wc:149852, 
		ss:"", sum:""  },
	{ title:"The Complete Tales of Edgar Allen Poe", author:"Poe", year:1846, done:false, genre:"19th", rank:{tgb:73}, wc:141041, 
		ss:"", sum:""  },
	{ title:"The Red and the Black", author:"Stendhal", year:1830, done:true, genre:"19th", rank:{tgb:34}, wc:154257, 
		ss:"", sum:""  },
	{ title:"The Charterhouse of Parma", author:"Stendhal", year:1839, done:false, genre:"19th", rank:{tgb:93}, wc:143244, 
		ss:"", sum:""  },
	// { title:"Uncle Tom’s Cabin", author:"Stowe", year:1852, done:false, genre:"personal", rank:{tgb:416} },
	{ title:"Vanity Fair", author:"Thackeray", year:1847, done:false, genre:"19th", rank:{tgb:81}, wc:172980, 
		ss:"", sum:""  },
	{ title:"Anna Karenina", author:"Tolstoy", year:1877, done:true, genre:"19th", rank:{tgb:19}, wc:237959, 
		ss:"", sum:""  },
	{ title:"War and Peace", author:"Tolstoy", year:1867, done:true, genre:"19th", rank:{tgb:7}, wc:317257, 
		ss:"", sum:""  },
	{ title:"Fathers and Sons", author:"Turgenev", year:1862, done:true, genre:"19th", rank:{tgb:113}, wc:81534, 
		ss:"", sum:""  },
	{ title:"The Adventures of Huckleberry Finn", author:"Twain", year:1884, done:true, genre:"19th", rank:{tgb:18}, wc:61685, 
		ss:"", sum:""  },
	{ title:"Picture of Dorian Gray", author:"Wilde", year:1890, done:true, genre:"personal", rank:{tgb:206}, wc:38528, 
		ss:"", sum:""  },
	{ title:"Portrait of a Lady", author:"James", year:1881, done:false, genre:"19th", rank:{tgb:63}, wc:182892, 
		ss:"", sum:""  },
	{ title:"The Ambassadors", author:"James", year:1903, done:false, genre:"19th", rank:{tgb:167}, wc:141041, 
		ss:"", sum:""  },
	
	// 20th Century Literature
	{ title:"The Master and Margarita", author:"Bulgakov", year:1966, done:true, genre:"20th", rank:{tgb:108}, wc:110753, 
		ss:"", sum:""  },
	{ title:"The Stories of Anton Chekhov", author:"Chekhov", year:1932, done:false, genre:"20th", rank:{tgb:39}, wc:167817, 
		ss:"", sum:""  },
	{ title:"Rebecca", author:"du Maurier", year:1938, done:false, genre:"20th", rank:{tgb:98}, wc:114609, 
		ss:"", sum:""  },
	{ title:"My Antonia", author:"Cather", year:1918, done:false, genre:"20th", rank:{tgb:145}, wc:36390, 
		ss:"", sum:""  },
	{ title:"Heart of Darkness", author:"Conrad", year:1902, done:true, genre:"20th", rank:{tgb:24}, wc:29155, 
		ss:"", sum:""  },
	{ title:"Nostromo", author:"Conrad", year:1904, done:false, genre:"20th", rank:{tgb:138}, wc:99827, 
		ss:"", sum:""  },
	{ title:"Lord Jim", author:"Conrad", year:1900, done:true, genre:"20th", rank:{tgb:123}, wc:83739, 
		ss:"", sum:""  },
	{ title:"The Sound and the Fury", author:"Falkner", year:1929, done:false, genre:"20th", rank:{tgb:25}, wc:89805, 
		ss:"", sum:""  },
	{ title:"As I Lay Dying", author:"Falkner", year:1930, done:true, genre:"20th", rank:{tgb:67}, wc:73540, 
		ss:"", sum:""  },
	{ title:"Absalom, Absalom!", author:"Falkner", year:1936, done:true, genre:"20th", rank:{tgb:30}, wc:86221, 
		ss:"", sum:""  },
	{ title:"The Great Gatsby", author:"Fitzgerald", year:1925, done:true, genre:"20th", rank:{tgb:5}, wc:49555, 
		ss:"", sum:""  },
	{ title:"Tender Is the Night", author:"Fitzgerald", year:1934, done:true, genre:"20th", rank:{tgb:149}, wc:88151, 
		ss:"", sum:""  },
	{ title:"The Good Soldier", author:"Ford", year:1915, done:false, genre:"20th", rank:{tgb:77}, wc:52863, 
		ss:"", sum:""  },
	{ title:"A Passage to India", author:"Forster", year:1924, done:true, genre:"20th", rank:{tgb:56}, wc:71058, 
		ss:"", sum:""  },
	{ title:"Howard’s End", author:"Forster", year:1910, done:false, genre:"20th", rank:{tgb:118}, wc:61134, 
		ss:"", sum:""  },
	{ title:"A Room with a View", author:"Forster", year:1908, done:false, genre:"20th", rank:{tgb:181}, wc:60264, 
		ss:"", sum:""  },
	{ title:"Invisible Man", author:"Ellison", year:1952, done:false, genre:"20th", rank:{tgb:31}, wc:160039, 
		ss:"", sum:""  },
	{ title:"The Sun Also Rises", author:"Hemingway", year:1926, done:true, genre:"20th", rank:{tgb:44}, wc:88151, 
		ss:"", sum:""  },
	{ title:"Stories of Ernest Hemingway", author:"Hemingway", year:1938, done:true, genre:"20th", rank:{tgb:137}, wc:179037, 
		ss:"", sum:""  },
	{ title:"The Old Man and the Sea", author:"Hemingway", year:1952, done:true, genre:"20th", rank:{tgb:57}, wc:35220, 
		ss:"", sum:""  },
	{ title:"For Whom the Bell Tolls", author:"Hemingway", year:1940, done:true, genre:"20th", rank:{tgb:60}, wc:132230, 
		ss:"", sum:""  },
	{ title:"A Farewell to Arms", author:"Hemingway", year:1929, done:false, genre:"20th", rank:{tgb:84}, wc:96972, 
		ss:"", sum:""  },
	{ title:"A Portrait of the Artist as a Young Man", author:"Joyce", year:1916, done:true, genre:"20th", rank:{tgb:49}, wc:105794, 
		ss:"", sum:""  },
	{ title:"Ulysses", author:"Joyce", year:1922, done:false, genre:"20th", rank:{tgb:2}, wc:202716, 
		ss:"", sum:""  },
	{ title:"Dubliners", author:"Joyce", year:1914, done:false, genre:"personal", rank:{tgb:243}, wc:101383, 
		ss:"", sum:""  },
	{ title:"The Golden Notebook", author:"Lessing", year:1962, done:false, genre:"20th", rank:{tgb:129}, wc:189500, 
		ss:"", sum:""  },
	{ title:"Call of the Wild", author:"London", year:1903, done:true, genre:"20th", rank:{tgb:148}, wc:15735, 
		ss:"", sum:""  },
	{ title:"Gone With the Wind", author:"Mitchell", year:1936, done:false, genre:"20th", rank:{tgb:70}, wc:271095, 
		ss:"", sum:""  },
	{ title:"In Search of Lost Time", author:"Proust", year:1913, done:false, genre:"20th", rank:{tgb:1}, wc:1328295, 
		ss:"", sum:""  },
	{ title:"The Grapes of Wrath", author:"Steinbeck", year:1939, done:true, genre:"20th", rank:{tgb:29}, wc:127824, 
		ss:"", sum:""  },
	{ title:"East of Eden", author:"Steinbeck", year:1952, done:true, genre:"personal", wc:190326, 
		ss:"", sum:""  },
	{ title:"Of Mice and Men", author:"Steinbeck", year:1937, done:true, genre:"20th", rank:{tgb:173}, wc:28879, 
		ss:"", sum:""  },
	{ title:"The Age of Innocence", author:"Wharton", year:1920, done:true, genre:"20th", rank:{tgb:74}, wc:47349, 
		ss:"", sum:""  },
	{ title:"The House of Mirth", author:"Wharton", year:1905, done:true, genre:"20th", rank:{tgb:199}, wc:101383, 
		ss:"", sum:""  },
	{ title:"Things Fall Apart", author:"Achebe", year:1958, done:true, genre:"20th", rank:{tgb:58}, wc:57550, 
		ss:"", sum:""  },
	{ title:"Collected Fiction", author:"Borges", year:1944, done:true, genre:"20th", rank:{tgb:43}, wc:155634, 
		ss:"", sum:""  },
	{ title:"The Stranger", author:"Camus", year:1942, done:true, genre:"20th", rank:{tgb:40}, wc:33841, 
		ss:"", sum:""  },
	{ title:"The Plague", author:"Camus", year:1947, done:false, genre:"20th", rank:{tgb:188}, wc:88151, 
		ss:"", sum:""  },
	{ title:"Journey to the End of the Night", author:"Celine", year:1932, done:false, genre:"20th", rank:{tgb:85}, wc:127824, 
		ss:"", sum:""  },
	{ title:"The Tin Drum", author:"Grass", year:1959, done:true, genre:"20th", rank:{tgb:110}, wc:163067, 
		ss:"", sum:""  },
	{ title:"The Quiet American", author:"Greene", year:1955, done:true, genre:"personal", rank:{tgb:470}, wc:49555, 
		ss:"", sum:""  },
	{ title:"Lord of the Flies", author:"Golding", year:1954, done:true, genre:"20th", rank:{tgb:71}, wc:61685, 
		ss:"", sum:""  },
	{ title:"Catch-22", author:"Heller", year:1953, done:true, genre:"20th", rank:{tgb:23}, wc:149852, 
		ss:"", sum:""  },
	{ title:"Their Eyes Were Watching God", author:"Hurston", year:1937, done:true, genre:"20th", rank:{tgb:104}, wc:60307, 
		ss:"", sum:""  },
	{ title:"The Complete Stories of Franz Kafka", author:"Kafka", year:1971, done:true, genre:"20th", rank:{tgb:61}, wc:134432, 
		ss:"", sum:""  },
	{ title:"The Castle", author:"Kafka", year:1926, done:true, genre:"20th", rank:{tgb:86}, wc:88151, 
		ss:"", sum:""  },
	{ title:"The Metamorphosis", author:"Kafka", year:1915, done:true, genre:"20th", rank:{tgb:61}, wc:14524, 
		ss:"", sum:""  },
	{ title:"The Trial", author:"Kafka", year:1925, done:true, genre:"20th", rank:{tgb:33}, wc:95924, 
		ss:"", sum:""  },
	{ title:"On the Road", author:"Kerouac", year:1957, done:true, genre:"20th", rank:{tgb:76}, wc:80707, 
		ss:"", sum:""  },
	{ title:"One Flew Over the Cuckoo's Nest", author:"Kesey", year:1962, done:false, genre:"20th", rank:{tgb:152}, wc:85820, 
		ss:"", sum:""  },
	{ title:"Sons and Lovers", author:"Lawrence", year:1913, done:false, genre:"20th", rank:{tgb:111}, wc:110202, 
		ss:"", sum:""  },
	// { title:"The Rainbow", author:"Lawrence", year:1915, done:false, genre:"personal", rank:{tgb:350} },
	{ title:"Women in Love", author:"Lawrence", year:1920, done:false, genre:"20th", rank:{tgb:172}, wc:163067, 
		ss:"", sum:""  },
	{ title:"To Kill a Mockingbird", author:"Lee", year:1960, done:true, genre:"20th", rank:{tgb:32}, wc:92562, 
		ss:"", sum:""  },
	{ title:"Under the Volcano", author:"Lowry", year:1947, done:false, genre:"20th", rank:{tgb:82}, wc:123419, 
		ss:"", sum:""  },
	{ title:"Buddenbrooks", author:"Mann", year:1901, done:false, genre:"20th", rank:{tgb:144}, wc:202227, 
		ss:"", sum:""  },
	{ title:"Doctor Faustus", author:"Mann", year:1947, done:true, genre:"20th", rank:{tgb:134}, wc:163724, 
		ss:"", sum:""  },
	// { title:"The Magic Mountain", author:"Mann", year:1924, done:false, genre:"personal" },
	{ title:"One Hundred Years of Solitude", author:"Marquez", year:1967, done:true, genre:"20th", rank:{tgb:4}, wc:114883, 
		ss:"", sum:""  },
	{ title:"The Man Without Qualities", author:"Musil", year:1943, done:false, genre:"20th", rank:{tgb:133}, wc:497000, 
		ss:"", sum:""  },
	{ title:"Lolita", author:"Nabokov", year:1955, done:true, genre:"20th", rank:{tgb:12}, wc:87323, 
		ss:"", sum:""  },
	{ title:"Pale Fire", author:"Nabokov", year:1962, done:true, genre:"20th", rank:{tgb:65}, wc:61685, 
		ss:"", sum:""  },
	{ title:"The Complete Stories of Flannery O’Connor", author:"O’Connor", year:1971, done:false, genre:"20th", rank:{tgb:121}, wc:158662, 
		ss:"", sum:""  },
	{ title:"The Bell Jar", author:"Plath", year:1963, done:true, genre:"personal", rank:{tgb:261}, wc:76979, 
		ss:"", sum:""  },
	{ title:"All Quiet on the Western Front", author:"Remarque", year:1929, done:true, genre:"20th", rank:{tgb:142}, wc:83739, 
		ss:"", sum:""  },
	{ title:"Wide Sargasso Sea", author:"Rhys", year:1966, done:true, genre:"20th", rank:{tgb:115}, wc:48452, 
		ss:"", sum:""  },
	{ title:"The Catcher in the Rye", author:"Salinger", year:1951, done:true, genre:"20th", rank:{tgb:16}, wc:79328, 
		ss:"", sum:""  },
	{ title:"Rabbit, Run", author:"Updike", year:1960, done:false, genre:"20th", rank:{tgb:122}, wc:92562, 
		ss:"", sum:""  },
	{ title:"Rabbit Redux", author:"Updike", year:1971, done:false, genre:"20th", rank:{tgb:176}, wc:123419, 
		ss:"", sum:""  },
	{ title:"Rabbit is Rich", author:"Updike", year:1981, done:false, genre:"20th", rank:{tgb:153}, wc:171656, 
		ss:"", sum:""  },
	{ title:"Rabbit at Rest", author:"Updike", year:1990, done:false, genre:"personal", rank:{tgb:217}, wc:167472, 
		ss:"", sum:""  },
	{ title:"Brideshead Revisited", author:"Waugh", year:1945, done:true, genre:"personal", rank:{tgb:274}, wc:119014, 
		ss:"", sum:""  },
	// { title:"Scoop", author:"Waugh", year:1938, done:false, genre:"personal", rank:{tgb:463} },
	{ title:"All the King's Men", author:"Warren", year:1946, done:false, genre:"20th", rank:{tgb:132}, wc:180689, 
		ss:"", sum:""  },
	{ title:"To the Lighthouse", author:"Woolf", year:1927, done:true, genre:"20th", rank:{tgb:22}, wc:57550, 
		ss:"", sum:""  },
	{ title:"Orlando: A Biography", author:"Woolf", year:1928, done:false, genre:"20th", rank:{tgb:79}, wc:96972, 
		ss:"", sum:""  },
	{ title:"Mrs. Dalloway", author:"Woolf", year:1925, done:true, genre:"20th", rank:{tgb:38}, wc:57275, 
		ss:"", sum:""  },
	{ title:"The Waves", author:"Woolf", year:1931, done:false, genre:"20th", rank:{tgb:175}, wc:60559, 
		ss:"", sum:""  },
	{ title:"Native Son", author:"Wright", year:1940, done:false, genre:"20th", rank:{tgb:92}, wc:149852, 
		ss:"", sum:""  },
	{ title:"Nineteen Eighty-Four", author:"Orwell", year:0, done:true, genre:"20th", rank:{tgb:26}, wc:90356, 
		ss:"", sum:""  },
	{ title:"Animal Farm", author:"Orwell", year:0, done:true, genre:"20th", rank:{tgb:78}, wc:38528, 
		ss:"", sum:""  },
	{ title:"Fear and Loathing in Las Vegas", author:"Thompson", year:1971, done:false, genre:"20th", rank:{tgb:130}, wc:54844, 
		ss:"", sum:""  },
	{ title:"The Moviegoer", author:"Percy", year:1961, done:false, genre:"20th", rank:{tgb:159}, wc:74918, 
		ss:"", sum:""  },
	{ title:"Pedro Paramo", author:"Rulfo", year:1955, done:false, genre:"20th", rank:{tgb:163}, wc:34117, 
		ss:"", sum:""  },
	{ title:"The Prime of Miss Jean Brodie", author:"Spark", year:1961, done:false, genre:"20th", rank:{tgb:164}, wc:44041, 
		ss:"", sum:""  },
	{ title:"Doctor Zhivago", author:"Pasternak", year:1957, done:false, genre:"20th", rank:{tgb:166}, wc:193905, 
		ss:"", sum:"" },
	{ title:"Confessions of Zeno", author:"Svevo", year:1923, done:false, genre:"20th", rank:{tgb:170}, wc:110825, 
		ss:"", sum:"" },
	{ title:"The Leopard", author:"Lampedusa", year:1958, done:false, genre:"20th", rank:{tgb:178}, wc:92562, 
		ss:"", sum:"" },
	{ title:"The Stories of John Cheever", author:"Cheever", year:1978, done:false, genre:"20th", rank:{tgb:191}, wc:193905, 
		ss:"", sum:"" },
	{ title:"The 42nd Parallel", author:"Dos Passos", year:1930, done:false, genre:"20th", rank:{tgb:196}, wc:123419, 
		ss:"", sum:"" },
	{ title:"Nineteen Nineteen", author:"Dos Passos", year:1932, done:false, genre:"20th", rank:{tgb:195}, wc:103000, 
		ss:"", sum:"" },
	{ title:"The Big Money", author:"Dos Passos", year:1936, done:false, genre:"20th", rank:{tgb:197}, wc:145446, 
		ss:"", sum:"" },
	{ title:"Independent People", author:"Laxness", year:1946, done:false, genre:"20th", rank:{tgb:198}, wc:137708, 
		ss:"", sum:"" },
	{ title:"The Jungle", author:"Sinclair", year:1906, done:true, genre:"personal", rank:{tgb:234}, wc:68853, 
		ss:"", sum:"" },
	{ title:"Gravity's Rainbow", author:"Pynchon", year:1973, done:false, genre:"personal", rank:{tgb:242}, wc:213730, 
		ss:"", sum:"" },
	{ title:"Steppenwolf", author:"Hesse", year:1927, done:false, genre:"personal", rank:{tgb:246}, wc:70000, 
		ss:"", sum:"" },
	{ title:"Siddhartha", author:"Hesse", year:1922, done:true, genre:"personal", rank:{tgb:266}, wc:48440, 
		ss:"", sum:"" },
	
	// 21st Century Literature
	{ title:"Beloved", author:"Morrison", year:1987, done:true, genre:"21st", rank:{tgb:37}, wc:88426, 
		ss:"", sum:""  },
	{ title:"Song of Solomon", author:"Morrison", year:1977, done:true, genre:"personal", rank:{tgb:239}, wc:96972, 
		ss:"", sum:""  },
	{ title:"White Teeth", author:"Smith", year:2000, done:false, genre:"21st", rank:{tgb:127}, wc:127824, 
		ss:"", sum:""  },
	{ title:"Love in the Time of Cholera", author:"Marquez", year:1985, done:true, genre:"21st", rank:{tgb:143}, wc:101383, 
		ss:"", sum:""  },
	{ title:"Americanah", author:"Adichie", year:2013, done:false, genre:"personal", wc:161966, 
		ss:"", sum:""  },
	{ title:"If on a Winter’s Night a Traveller", author:"Calvino", year:1979, done:false, genre:"personal", rank:{tgb:225}, wc:82031, 
		ss:"", sum:""  },
	{ title:"The Brief Wondrous Life of Oscar Wao", author:"Diaz", year:2007, done:false, genre:"21st", rank:{tgb:156}, wc:93388, 
		ss:"", sum:""  },
	{ title:"The Corrections", author:"Franzen", year:2001, done:false, genre:"21st", rank:{tgb:147}, wc:158662, 
		ss:"", sum:""  },
	{ title:"Remains of the Day", author:"Ishiguro", year:1989, done:false, genre:"21st", rank:{tgb:168}, wc:67474, 
		ss:"", sum:""  },
	{ title:"The Unbearable Lightness of Being", author:"Kundera", year:1984, done:true, genre:"personal", rank:{tgb:256}, wc:88151, 
		ss:"", sum:""  },
	{ title:"Atonement", author:"McEwan", year:2001, done:false, genre:"21st", rank:{tgb:125}, wc:96696, 
		ss:"", sum:""  },
	{ title:"The Wind-Up Bird Chronicle", author:"Murakami", year:1994, done:true, genre:"21st", rank:{tgb:187}, wc:182677, 
		ss:"", sum:""  },
	{ title:"Midnight’s Children", author:"Rushdie", year:1981, done:false, genre:"21st", rank:{tgb:50}, wc:147649, 
		ss:"", sum:""  },
	{ title:"Confederacy of Dunces", author:"Toole", year:1980, done:false, genre:"21st", rank:{tgb:124}, wc:111579, 
		ss:"", sum:""  },
	{ title:"The Color Purple", author:"Walker", year:1982, done:false, genre:"21st", rank:{tgb:68}, wc:83739, 
		ss:"", sum:""  },
	{ title:"On Earth We're Briefly Gorgeous", author:"Vuong", year:2019, done:true, genre:"personal", wc:63655, 
		ss:"", sum:""  },
	{ title:"A Prayer for Owen Meany", author:"Irving", year:1989, done:false, genre:"21st", rank:{tgb:151}, wc:172704, 
		ss:"", sum:"" },
	{ title:"The World According to Garp", author:"Irving", year:1978, done:false, genre:"21st", rank:{tgb:200}, wc:171879, 
		ss:"", sum:"" },
	{ title:"Austerlitz", author:"Sebald", year:2001, done:false, genre:"21st", rank:{tgb:169}, wc:88151, 
		ss:"", sum:"" },
	{ title:"2666", author:"Bolaño", year:2004, done:false, genre:"21st", rank:{tgb:179}, wc:251175, 
		ss:"", sum:"" },
	{ title:"The Sea, The Sea", author:"Murdoch", year:1978, done:false, genre:"21st", rank:{tgb:182}, wc:145446, 
		ss:"", sum:"" },
	{ title:"The Bonfire of the Vanities", author:"Wolfe", year:1987, done:false, genre:"21st", rank:{tgb:183}, wc:193905, 
		ss:"", sum:"" },
	{ title:"The House of the Spirits", author:"Allende", year:1982, done:false, genre:"21st", rank:{tgb:184}, wc:136635, 
		ss:"", sum:"" },
	{ title:"The Amazing Adventures of Kavalier and Clay", author:"Chabon", year:2000, done:true, genre:"personal", rank:{tgb:229}, wc:191765, 
		ss:"", sum:""  },
	
	// Biography and Memoir
	{ title:"I Know Why the Caged Bird Sings", author:"Angelou", year:1969, done:true, genre:"biography", wc:83739, 
		ss:"", sum:""  },
	{ title:"Borderlands/La Frontera: The New Mestiza", author:"Anzaldua", year:1987, done:false, genre:"biography", wc:83915, 
		ss:"", sum:""  },
	{ title:"Confessions", author:"Augustine", year:397, done:false, genre:"biography", wc:83645, 
		ss:"", sum:""  },
	{ title:"Alexander Hamilton", author:"Chernow", year:2004, done:true, genre:"biography", wc:219969, 
		ss:"", sum:""  },
	{ title:"A Year of Magical Thinking", author:"Didion", year:2005, done:true, genre:"biography", wc:61035, 
		ss:"", sum:""  },
	{ title:"Narrative of the Life of Frederick Douglass", author:"Douglass", year:1845, done:true, genre:"biography", wc:46769, 
		ss:"", sum:""  },
	{ title:"Nickel and Dimed", author:"Ehrenreich", year:2001, done:true, genre:"biography", wc:68841, 
		ss:"", sum:""  },
	{ title:"Diary of a Young Girl", author:"Frank", year:1947, done:true, genre:"biography", wc:85731, 
		ss:"", sum:""  },
	{ title:"The Autobiography of Malcolm X", author:"Haley", year:1965, done:true, genre:"biography", wc:123729, 
		ss:"", sum:""  },
	{ title:"Alan Turing: The Enigma", author:"Hodges", year:1983, done:true, genre:"personal", wc:206528, 
		ss:"", sum:""  },
	{ title:"When Breath Becomes Air", author:"Kalanithi", year:2016, done:true, genre:"biography", wc:48575, 
		ss:"", sum:""  },
	{ title:"My First Summer in the Sierra", author:"Muir", year:1911, done:true, genre:"biography", wc:48922, 
		ss:"", sum:""  },
	{ title:"Speak, Memory", author:"Nabokov", year:1951, done:true, genre:"biography", wc:90375, 
		ss:"", sum:""  },
	{ title:"Dreams from my Father", author:"Obama", year:1995, done:true, genre:"biography", wc:124804, 
		ss:"", sum:""  },
	{ title:"Confessions", author:"Rousseau", year:1782, done:false, genre:"biography", wc:198311, 
		ss:"", sum:""  },
	{ title:"Up From Slavery", author:"Washington", year:1901, done:true, genre:"biography", wc:41164, 
		ss:"", sum:""  },
	{ title:"The Double Helix", author:"Watson", year:1968, done:true, genre:"biography", wc:68841, 
		ss:"", sum:""  },
	{ title:"Hillbilly Elegy", author:"Vance", year:2016, done:true, genre:"biography", wc:77454, 
		ss:"", sum:""  },
	
	// Children's Literature
	{ title:"Little Women", author:"Alcott", year:1868, done:false, genre:"children", rank:{tgb:119}, wc:95830, 
		ss:"", sum:""  },
	{ title:"Fairy Tales and Stories", author:"Anderson", year:1837, done:true, genre:"children", rank:{tgb:120}, wc:149284, 
		ss:"", sum:""  },
	{ title:"Charlotte's Web", author:"White", year:1952, done:true, genre:"children", rank:{tgb:91}, wc:50658, 
		ss:"", sum:""  },
	{ title:"Alice's Adventures in Wonderland", author:"Carroll", year:1865, done:true, genre:"children", rank:{tgb:20}, wc:24192, 
		ss:"", sum:""  },
	{ title:"Through the Looking Glass", author:"Carroll", year:1871, done:true, genre:"children", rank:{tgb:249}, wc:28013, 
		ss:"", sum:""  },
	{ title:"The Wind in the Willows", author:"Grahame", year:1908, done:true, genre:"children", rank:{tgb:150}, wc:46665, 
		ss:"", sum:""  },
	{ title:"Treasure Island", author:"Stevenson", year:1883, done:false, genre:"children", rank:{tgb:131}, wc:66096, 
		ss:"", sum:""  },
	{ title:"The Little Prince", author:"Saint-Exupery", year:1943, done:false, genre:"children", rank:{tgb:112}, wc:28846, 
		ss:"", sum:""  },
	{ title:"His Dark Materials", author:"Pullman", year:1997, done:true, genre:"personal", rank:{tgb:413}, wc:400000, 
		ss:"", sum:""  },
	{ title:"Harry Potter", author:"Rowling", year:1997, done:true, genre:"children", rank:{tgb:209}, wc:1250000, 
		ss:"", sum:""  },
	{ title:"The Lion, the Witch and the Wardrobe", author:"Lewis", year:1950, done:true, genre:"children", rank:{tgb:157}, wc:57275, 
		ss:"", sum:""  },
	{ title:"A Tree Grows in Brooklyn", author:"Smith", year:1943, done:false, genre:"children", rank:{tgb:165}, wc:136635, 
		ss:"", sum:""  },
	{ title:"Winnie the Pooh", author:"Milne", year:1926, done:false, genre:"children", rank:{tgb:214}, wc:32933, 
		ss:"", sum:""  },
	
	// Commentary
	{ title:"Notes of a Native Son", author:"Baldwin", year:1955, done:true, genre:"commentary", wc:55921, 
		ss:"", sum:""  },
	{ title:"The Fire Next Time", author:"Baldwin", year:1963, done:false, genre:"commentary", wc:34387, 
		ss:"", sum:""  },
	{ title:"Slouching Toward Bethlehem", author:"Didion", year:1968, done:true, genre:"commentary", wc:77545, 
		ss:"", sum:""  },
	{ title:"Writings of Emerson", author:"Emerson", year:1885, done:true, genre:"commentary", wc:236637, 
		ss:"", sum:""  },
	{ title:"Being Mortal", author:"Gawande", year:2014, done:true, genre:"commentary", wc:81761, 
		ss:"", sum:""  },
	{ title:"Essays", author:"Montaigne", year:1580, done:true, genre:"commentary", wc:111901, 
		ss:"", sum:""  },
	{ title:"How to Do Nothing: Resisting the Attention Economy", author:"Odell", year:2019, done:true, genre:"personal", wc:68841, 
		ss:"", sum:""  },
	{ title:"Essays of George Orwell", author:"Orwell", year:1970, done:false, genre:"commentary", wc:152880, 
		ss:"", sum:""  },
	{ title:"Pensees", author:"Pascal", year:1670, done:false, genre:"commentary", wc:101383, 
		ss:"", sum:""  },
	{ title:"Against Interpretation", author:"Sontag", year:1966, done:false, genre:"commentary", wc:90375, 
		ss:"", sum:""  },
	{ title:"Walden, or Life in the Woods", author:"Thoreau", year:1854, done:true, genre:"commentary", wc:53966, 
		ss:"", sum:""  },
	{ title:"A Room of One’s Own", author:"Woolf", year:1929, done:true, genre:"commentary", wc:35220, 
		ss:"", sum:""  },
	
	// Drama
	{ title:"Who's Afraid of Virginia Woolf?", author:"Albee", year:1962, done:false, genre:"drama", wc:74918, 
		ss:"", sum:""  },
	{ title:"Waiting for Godot", author:"Beckett", year:1953, done:true, genre:"drama", rank:{tgb:102}, wc:35220, 
		ss:"", sum:""  },
	{ title:"Faust", author:"Goethe", year:1829, done:false, genre:"drama", rank:{tgb:97}, wc:133407, 
		ss:"", sum:""  },
	{ title:"A Raisin in the Sun", author:"Hansberry", year:1959, done:true, genre:"drama", wc:41560, 
		ss:"", sum:""  },
	{ title:"A Doll’s House", author:"Ibsen", year:1879, done:true, genre:"drama", rank:{tgb:216}, wc:21987, 
		ss:"", sum:""  },
	{ title:"Peer Gynt", author:"Ibsen", year:1876, done:false, genre:"drama", wc:46523, 
		ss:"", sum:""  },
	{ title:"Angels In America", author:"Kushner", year:1991, done:true, genre:"drama", wc:81761, 
		ss:"", sum:""  },
	{ title:"The Crucible", author:"Miller", year:1953, done:true, genre:"drama", wc:39354, 
		ss:"", sum:""  },
	{ title:"Death of a Salesman", author:"Miller", year:1949, done:true, genre:"drama", wc:38252, 
		ss:"", sum:""  },
	{ title:"Tartuffe", author:"Moliere", year:1664, done:false, genre:"drama", wc:45144, 
		ss:"", sum:""  },
	{ title:"Long Day's Journey Into Night", author:"O'Neill", year:1956, done:false, genre:"drama", wc:52863, 
		ss:"", sum:""  },
	{ title:"The Iceman Cometh", author:"O'Neill", year:1946, done:true, genre:"drama", wc:58882, 
		ss:"", sum:""  },
	{ title:"Hamlet", author:"Shakespeare", year:1609, done:true, genre:"drama", rank:{tgb:8}, wc:94216, 
		ss:"", sum:""  },
	{ title:"King Lear", author:"Shakespeare", year:1606, done:true, genre:"drama", rank:{tgb:106}, wc:96972, 
		ss:"", sum:""  },
	{ title:"Macbeth", author:"Shakespeare", year:1606, done:false, genre:"drama", rank:{tgb:161}, wc:83739, 
		ss:"", sum:""  },
	{ title:"A Midsummer Night's Dream", author:"Shakespeare", year:1605, done:true, genre:"drama", rank:{tgb:498}, wc:70507, 
		ss:"", sum:""  },
	{ title:"Othello", author:"Shakespeare", year:1604, done:false, genre:"drama", rank:{tgb:494}, wc:86497, 
		ss:"", sum:""  },
	{ title:"The Tempest", author:"Shakespeare", year:1611, done:false, genre:"drama", rank:{tgb:140}, wc:58612, 
		ss:"", sum:""  },
	{ title:"A Streetcar Named Desire", author:"Williams", year:1947, done:false, genre:"drama", wc:30533, 
		ss:"", sum:""  },
	{ title:"The Glass Menagerie", author:"Williams", year:1945, done:true, genre:"drama", wc:28604, 
		ss:"", sum:""  },
	
	// Genre fiction
	{ title:"The Hitchhiker’s Guide to the Galaxy", author:"Adams", year:1981, done:true, genre:"genre", rank:{tgb:207}, wc:233244, 
		ss:"", sum:""  },
	{ title:"The Handmaid’s Tale", author:"Atwood", year:1985, done:true, genre:"genre", rank:{tgb:90}, wc:83645, 
		ss:"", sum:""  },
	{ title:"Foundation", author:"Asimov", year:1942, done:true, genre:"personal", rank:{tgb:379}, wc:82992, 
		ss:"", sum:""  },
	{ title:"Clockwork Orange", author:"Burgess", year:1962, done:true, genre:"genre", rank:{tgb:107}, wc:66096, 
		ss:"", sum:""  },
	{ title:"The Big Sleep", author:"Chandler", year:1939, done:false, genre:"genre", rank:{tgb:139}, wc:69966, 
		ss:"", sum:""  },
	{ title:"Do Androids Dream of Electric Sheep", author:"Dick", year:1968, done:true, genre:"personal", rank:{tgb:422}, wc:67277, 
		ss:"", sum:""  },
	{ title:"Neuromancer", author:"Gibson", year:1984, done:true, genre:"personal", rank:{tgb:400}, wc:94216, 
		ss:"", sum:""  },
	{ title:"Dune", author:"Herbert", year:1965, done:true, genre:"genre", rank:{tgb:220}, wc:211858, 
		ss:"", sum:""  },
	{ title:"Brave New World", author:"Huxley", year:1932, done:true, genre:"genre", rank:{tgb:72}, wc:80746, 
		ss:"", sum:""  },
	{ title:"Blood Meridian", author:"McCarthy", year:1985, done:false, genre:"genre", rank:{tgb:146}, wc:101383, 
		ss:"", sum:""  },
	{ title:"The Road", author:"McCarthy", year:2006, done:false, genre:"genre", rank:{tgb:224}, wc:79053, 
		ss:"", sum:""  },
	{ title:"Frankenstein", author:"Shelley", year:1823, done:true, genre:"genre", rank:{tgb:64}, wc:76257, 
		ss:"", sum:""  },
	{ title:"The Strange Case of Dr. Jekyll and Mr. Hyde", author:"Stevenson", year:1886, done:false, genre:"genre", rank:{tgb:189}, wc:70507, 
		ss:"", sum:""  },
	{ title:"Dracula", author:"Stoker", year:1897, done:true, genre:"genre", rank:{tgb:171}, wc:66155, 
		ss:"", sum:""  },
	{ title:"Lord of the Rings", author:"Tolkien", year:1954, done:true, genre:"genre", rank:{tgb:53}, wc:354455, 
		ss:"", sum:""  },
	{ title:"The Hobbit", author:"Tolkien", year:1937, done:true, genre:"genre", rank:{tgb:193}, wc:90287, 
		ss:"", sum:""  },
	{ title:"Twenty Thousand Leagues Under the Sea", author:"Verne", year:1870, done:true, genre:"genre", rank:{tgb:185}, wc:71767, 
		ss:"", sum:""  },
	{ title:"Slaughterhouse-Five", author:"Vonnegut", year:1969, done:true, genre:"genre", rank:{tgb:89}, wc:80746, 
		ss:"", sum:""  },
	{ title:"The Time Machine", author:"Wells", year:1895, done:true, genre:"genre", rank:{tgb:237}, wc:44829, 
		ss:"", sum:""  },
	{ title:"The Complete Sherlock Holmes", author:"Doyle", year:1892, done:true, genre:"genre", rank:{tgb:174}, wc:494574, 
		ss:"", sum:""  },
	{ title:"Hound of the Baskervilles", author:"Doyle", year:1902, done:true, genre:"genre", rank:{tgb:177}, wc:70507, 
		ss:"", sum:""  },
	{ title:"Fahrenheit 451", author:"Bradbury", year:1953, done:true, genre:"genre", rank:{tgb:192}, wc:69803, 
		ss:"", sum:""  },
	{ title:"Stranger in a Strange Land", author:"Heinlein", year:1961, done:true, genre:"genre", rank:{tgb:213}, wc:170465, 
		ss:"", sum:""  },
	{ title:"2001: A Space Odyssey", author:"Clarke", year:1968, done:false, genre:"personal", rank:{tgb:258}, wc:82992, 
		ss:"", sum:""  },

	
	// Historical narrative
	{ title:"Bury My Heart at Wounded Knee", author:"Brown", year:1970, done:false, genre:"historical", wc:126305, 
		ss:"", sum:""  },
	{ title:"In Cold Blood", author:"Capote", year:1965, done:true, genre:"historical", wc:94491, 
		ss:"", sum:""  },
	{ title:"Black Reconstruction in America", author:"DuBois", year:1935, done:false, genre:"historical", wc:200000, 
		ss:"", sum:""  },
	{ title:"Hiroshima", author:"Hersey", year:1946, done:false, genre:"historical", wc:37526, 
		ss:"", sum:""  },
	{ title:"The Death and Life of Great American Cities", author:"Jacobs", year:1961, done:true, genre:"historical", wc:123191, 
		ss:"", sum:""  },
	{ title:"Modern Times", author:"Johnson", year:1983, done:false, genre:"historical", wc:236637, 
		ss:"", sum:""  },
	{ title:"This Radical Land", author:"Miller", year:2018, done:true, genre:"personal", wc:88221, 
		ss:"", sum:""  },
	{ title:"Making of the Atomic Bomb", author:"Rhodes", year:1986, done:true, genre:"historical", wc:240938, 
		ss:"", sum:""  },
	{ title:"And the Band Played On", author:"Shilts", year:1987, done:false, genre:"historical", wc:198724, 
		ss:"", sum:""  },
	{ title:"Working", author:"Terkel", year:1974, done:false, genre:"historical", wc:193879, 
		ss:"", sum:""  },
		
	// Literary criticism, rhetoric and style
	{ title:"Selected Essays", author:"Eliot", year:1932, done:false, genre:"criticism", wc:144160, 
		ss:"", sum:""  },
	{ title:"Aspects of the Novel", author:"Forster", year:1927, done:true, genre:"criticism", wc:51614, 
		ss:"", sum:""  },
	{ title:"The Great Tradition", author:"Leavis", year:1948, done:false, genre:"criticism", wc:83739, 
		ss:"", sum:""  },
	{ title:"Elements of Style", author:"Strunk and White", year:1918, done:true, genre:"criticism", wc:20000, 
		ss:"", sum:""  },
		
	// Poetry
	{ title:"The Flowers of Evil", author:"Baudelaire", year:1857, done:false, genre:"poetry", rank:{tgb:99}, wc:77454, 
		ss:"", sum:""  },
	{ title:"Poems of Emily Dickinson", author:"Dickinson", year:1890, done:true, genre:"poetry", rank:{tgb:96}, wc:83915, 
		ss:"", sum:""  },
	{ title:"The Waste Land", author:"Eliot", year:1922, done:true, genre:"poetry", rank:{tgb:83}, wc:10000, 
		ss:"", sum:""  },
	{ title:"Poems of Robert Frost", author:"Frost", year:1962, done:true, genre:"poetry", rank:{tgb:236}, wc:172118, 
		ss:"", sum:""  },
	{ title:"Howl", author:"Ginsberg", year:1956, done:true, genre:"personal", wc:15276, 
		ss:"", sum:""  },
	{ title:"Paradise Lost", author:"Milton", year:1667, done:true, genre:"poetry", rank:{tgb:94}, wc:141041, 
		ss:"", sum:""  },
	{ title:"A Season in Hell", author:"Rimbaud", year:1873, done:false, genre:"poetry", rank:{tgb:117}, wc:10000, 
		ss:"", sum:""  },
	{ title:"Poems of Alfred Tennyson", author:"Tennyson", year:1898, done:false, genre:"personal", wc:185022, 
		ss:"", sum:""  },
	{ title:"Leaves of Grass", author:"Whitman", year:1855, done:true, genre:"poetry", rank:{tgb:48}, wc:43000, 
		ss:"", sum:""  },
	{ title:"Poems of W.B. Yeats", author:"Yeats", year:1940, done:false, genre:"poetry", rank:{tgb:155}, wc:116202, 
		ss:"", sum:""  },
	
	// Wisdom Literature
	{ title:"Meditations", author:"Aurelius", year:180, done:false, genre:"wisdom", wc:70507, 
		ss:"", sum:""  },
	{ title:"The Quran", author:"Muhammad", year:610, done:false, genre:"wisdom", wc:135020, 
		ss:"", sum:""  },
	{ title:"Bhagavad-Gita: The Song of God", author:"Various", year:"c. 200 BCE", done:true, genre:"wisdom", wc:44491, 
		ss:"", sum:""  },
	{ title:"The Pentateuch", author:"Various", year:"c. 1000 BCE", done:false, genre:"wisdom", wc:150000, 
		ss:"", sum:""  },
	{ title:"The Book of Job", author:"Various", year:"c. 500 CE", done:true, genre:"wisdom", wc:18098, 
		ss:"", sum:""  },
	{ title:"The New Testament", author:"Various", year:"c. 100", done:false, genre:"wisdom", wc:184600, 
		ss:"", sum:""  },
	
	// Applied Science
	{ title:"The Intelligent Investor", author:"Graham", year:1949, done:false, genre:"business", wc:172118, 
		ss:"", sum:""  },
	{ title:"Making the Most of Your Money Now", author:"Quinn", year:1991, done:true, genre:"business", wc:316000, 
		ss:"", sum:""  },
	{ title:"How to Win Friends and Influence People", author:"Carnegie", year:1936, done:true, genre:"communications", wc:77454, 
		ss:"", sum:""  },
	{ title:"Influence", author:"Cialdini", year:1984, done:false, genre:"communications", wc:90375, 
		ss:"", sum:""  },
	{ title:"Wheels, Clocks, and Rockets: A History of Technology", author:"Cardwell", year:1994, done:false, genre:"engineering", wc:159752, 
		ss:"", sum:""  },
	{ title:"The Emperor of All Maladies", author:"Mukherjee", year:2010, done:true, genre:"medicine", wc:163515, 
		ss:"", sum:""  },
	{ title:"The Greatest Benefit to Mankind: A Medical History of Humanity", author:"Porter", year:1997, done:false, genre:"medicine", wc:234486, 
		ss:"", sum:""  },
	{ title:"The Codex", author:"Alexander", year:2017, done:false, genre:"rationality", wc:0, 
		ss:"", sum:""  },
	{ title:"The Most Good You Can Do", author:"Singer", year:2015, done:false, genre:"personal", wc:62381, 
		ss:"", sum:""  },
	{ title:"80,000 Hours", author:"Todd", year:2016, done:false, genre:"personal", wc:91990, 
		ss:"", sum:""  },
	{ title:"Rationality: A-Z", author:"Yudkowsky", year:2017, done:false, genre:"rationality", wc:0, 
		ss:"", sum:""  },
	{ title:"What You Should Know About Politics… But Don’t", author:"Conrad", year:2008, done:false, genre:"policy", wc:102000, 
		ss:"", sum:""  },
	{ title:"Are Prisons Obsolete?", author:"Davis", year:2003, done:false, genre:"policy", wc:34387, 
		ss:"", sum:""  },
	{ title:"Law 101", author:"Feinman", year:2000, done:true, genre:"policy", wc:94000, 
		ss:"", sum:""  },
	{ title:"The Everything American Government Book", author:"Ragone", year:2004, done:false, genre:"policy", wc:80000, 
		ss:"", sum:""  },
	{ title:"Superintelligence: Paths, Dangers, Strategies", author:"Bostrom", year:2014, done:false, genre:"policy", wc:124265, 
		ss:"", sum:""  },
	{ title:"Managing Your Mind", author:"Butler", year:1995, done:false, genre:"psychiatry", wc:202227, 
		ss:"", sum:""  },
	{ title:"The Portable Jung", author:"Jung", year:1976, done:false, genre:"psychiatry", wc:177226, 
		ss:"", sum:""  },
	{ title:"The Freud Reader", author:"Freud", year:1989, done:false, genre:"psychiatry", wc:240938, 
		ss:"", sum:""  },
	{ title:"On Becoming a Person", author:"Rogers", year:1956, done:false, genre:"psychiatry", wc:112976, 
		ss:"", sum:""  },
	
	// Formal Science
	{ title:"Computer: A History of the Information Machine", author:"Campbell-Kelly and Aspray", year:1996, done:false, genre:"computer", wc:101680, 
		ss:"", sum:""  },
	{ title:"The Ethical Algorithm", author:"Kearns and Roth", year:2019, done:false, genre:"personal", wc:58000, 
		ss:"", sum:""  },
	// { title:"Proofs from THE BOOK. (Number Theory, Combinatorics, Graph Theory)", author:"Aigner and Zeigler", year:1998, done:false, genre:"personal" },
	{ title:"The Princeton Companion to Mathematics", author:"Gowers", year:2008, done:false, genre:"math", wc:0, 
		ss:"", sum:""  },
	{ title:"The Norton History of the Mathematical Sciences", author:"Grattan-Guinness", year:1997, done:false, genre:"math", wc:208000, 
		ss:"", sum:""  },
	{ title:"Remarkable Mathematicians: From Euler to von Neumann", author:"James", year:2002, done:true, genre:"math", wc:120503, 
		ss:"", sum:""  },
	{ title:"A Concise History of Mathematics", author:"Struik", year:1948, done:true, genre:"math", wc:68841, 
		ss:"", sum:""  },
	{ title:"Pragmatism", author:"James", year:1907, done:true, genre:"philosophy", wc:35220, 
		ss:"", sum:""  },
	{ title:"The Republic", author:"Plato", year:"c. 380 BCE", done:true, genre:"philosophy", rank:{tgb:201}, wc:82636, 
		ss:"", sum:""  },
	// Natural Science
	{ title:"The Structure of Scientific Revolutions", author:"Kuhn", year:1962, done:true, genre:"natural", wc:70994, 
		ss:"", sum:""  },
	{ title:"Coming of Age in the Milky Way", author:"Ferris", year:1988, done:true, genre:"astronomy", wc:137708, 
		ss:"", sum:""  },
	{ title:"The Norton History of Astronomy and Cosmology", author:"North", year:1994, done:false, genre:"astronomy", wc:161365, 
		ss:"", sum:""  },
	{ title:"On the Origin of Species", author:"Darwin", year:1859, done:true, genre:"biology", wc:158662, 
		ss:"", sum:""  },
	{ title:"The Selfish Gene", author:"Dawkins", year:1976, done:true, genre:"biology", wc:146311, 
		ss:"", sum:""  },
	{ title:"Life on a Young Planet: The First Three Billion Years of Evolution on Earth", author:"Knoll", year:2003, done:false, genre:"biology", wc:79608, 
		ss:"", sum:""  },
	{ title:"What is Life?", author:"Schrodinger", year:1944, done:false, genre:"biology", wc:52691, 
		ss:"", sum:""  },
	{ title:"The Epic History of Biology", author:"Serafini", year:1993, done:false, genre:"biology", wc:109750, 
		ss:"", sum:""  },
	{ title:"Lives of a Cell", author:"Thomas", year:1974, done:true, genre:"biology", wc:43000, 
		ss:"", sum:""  },
	{ title:"The Chemical Tree: A History of Chemistry (Norton History of Science)", author:"Brock", year:1993, done:false, genre:"chemistry", wc:200076, 
		ss:"", sum:""  },
	{ title:"A Short History of Chemistry", author:"Partington", year:1937, done:false, genre:"chemistry", wc:120503, 
		ss:"", sum:""  },
	{ title:"Drawdown", author:"Hawken", year:2017, done:false, genre:"ecology", wc:68841, 
		ss:"", sum:""  },
	{ title:"The Uninhabitable Earth", author:"Wallace-Wells", year:2019, done:true, genre:"earth", wc:103295, 
		ss:"", sum:""  },
	{ title:"New Views on an Old Planet", author:"Van Andel", year:1985, done:false, genre:"earth", wc:123191, 
		ss:"", sum:""  },
	{ title:"The Earth Encompassed: A History of the Environmental Sciences (Norton History of Science)", author:"Bowler", year:1992, done:false, genre:"ecology", wc:180720, 
		ss:"", sum:""  },
	{ title:"Silent Spring", author:"Carson", year:1962, done:true, genre:"ecology", wc:107599, 
		ss:"", sum:""  },
	{ title:"The Sixth Extinction", author:"Kolbert", year:2014, done:false, genre:"ecology", wc:90375, 
		ss:"", sum:""  },
	{ title:"Evolution of Physics", author:"Einstein and Infield", year:1938, done:true, genre:"physics", wc:86068, 
		ss:"", sum:""  },
	{ title:"Relativity: the Special and General Theory", author:"Einstein", year:1916, done:false, genre:"physics", wc:51614, 
		ss:"", sum:""  },
	{ title:"Six Easy Pieces and Six Not-So-Easy Pieces", author:"Feynman", year:1963, done:false, genre:"physics", wc:96000, 
		ss:"", sum:""  },
	{ title:"A Brief History of Time", author:"Hawking", year:1988, done:true, genre:"physics", wc:56997, 
		ss:"", sum:""  },
	
	// Social Science
	{ title:"The Norton History of the Human Sciences (The Norton History of Science)", author:"Smith", year:1997, done:false, genre:"social", wc:286101, 
		ss:"", sum:""  },
	// Anthropology
	{ title:"The Mind of Primitive Man", author:"Boas", year:1911, done:false, genre:"anthropology", wc:82838, 
		ss:"", sum:""  },
	{ title:"Purity and Danger: An Analysis of Pollution and Taboo", author:"Douglas", year:1966, done:false, genre:"anthropology", wc:73148, 
		ss:"", sum:""  },
	{ title:"Elementary Forms of Religious Life", author:"Durkheim", year:1912, done:false, genre:"anthropology", wc:111901, 
		ss:"", sum:""  },
	{ title:"Interpretation of Cultures", author:"Geertz", year:1973, done:false, genre:"anthropology", wc:154913, 
		ss:"", sum:""  },
	{ title:"Myth and Meaning: Cracking the Code of Culture", author:"Levi-Strauss", year:1978, done:false, genre:"anthropology", wc:21467, 
		ss:"", sum:""  },
	{ title:"Tristes Tropiques", author:"Levi-Strauss", year:1955, done:true, genre:"anthropology", wc:120503, 
		ss:"", sum:""  },
	{ title:"The Gift: The Form and Reason for Exchange in Archaic Societies", author:"Mauss", year:1925, done:false, genre:"anthropology", wc:49461, 
		ss:"", sum:""  },
	{ title:"Magic, Science and Religion and the Scope of Rationality", author:"Tambiah", year:1990, done:false, genre:"anthropology", wc:53767, 
		ss:"", sum:""  },
	// Gender, sex and family
	{ title:"Women, Race & Class", author:"Davis", year:1981, done:false, genre:"gender", wc:71040, 
		ss:"", sum:""  },
	{ title:"The Second Sex", author:"de Beauvoir", year:1949, done:false, genre:"gender", wc:223733, 
		ss:"", sum:""  },
	{ title:"Hunger: A Memoir of (My) Body", author:"Gay", year:2017, done:true, genre:"gender", wc:86068, 
		ss:"", sum:""  },
	{ title:"Stone Butch Blues", author:"Feinberg", year:1993, done:false, genre:"gender", wc:88151, 
		ss:"", sum:""  },
	{ title:"The Feminine Mystique", author:"Friedan", year:1963, done:false, genre:"gender", wc:161365, 
		ss:"", sum:""  },
	{ title:"Feminism is for Everybody: Passionate Politics", author:"hooks", year:2000, done:true, genre:"gender", wc:37079, 
		ss:"", sum:""  },
	{ title:"Families We Choose: Lesbians, Gays, Kinship", author:"Weston", year:1991, done:false, genre:"gender", wc:77454, 
		ss:"", sum:""  },
	// Economics
	{ title:"Division of Labor in Society", author:"Durkheim", year:1893, done:false, genre:"economics", wc:111901, 
		ss:"", sum:""  },
	{ title:"The Communist Manifesto", author:"Marx and Engels", year:1848, done:false, genre:"economics", wc:12853, 
		ss:"", sum:""  },
	{ title:"The Wealth of Nations", author:"Smith", year:1776, done:true, genre:"economics", wc:339867, 
		ss:"", sum:""  },
	{ title:"The Protestant Ethic and the Spirit of Capitalism", author:"Weber", year:1905, done:false, genre:"economics", wc:105448, 
		ss:"", sum:""  },
	// Language and Linguistics
	{ title:"The Language Instinct: How the Mind Creates Language", author:"Pinker", year:1994, done:true, genre:"language", wc:154913, 
		ss:"", sum:""  },
	// Political Science
	{ title:"The Origins of Totalitarianism", author:"Arendt", year:1951, done:false, genre:"political", wc:154913, 
		ss:"", sum:""  },
	{ title:"End of History and the Last Man", author:"Fukuyama", year:1992, done:false, genre:"political", wc:124804, 
		ss:"", sum:""  },
	{ title:"Democracy in America", author:"De Toqueville", year:1835, done:true, genre:"political", wc:194162, 
		ss:"", sum:""  },
	{ title:"Leviathan", author:"Hobbes", year:1651, done:false, genre:"political", wc:110288, 
		ss:"", sum:""  },
	{ title:"The Social Contract", author:"Rousseau", year:1762, done:false, genre:"political", wc:52863, 
		ss:"", sum:""  },
	// Psychology
	{ title:"The Social Animal", author:"Aronson", year:1972, done:false, genre:"psychology", wc:129106, 
		ss:"", sum:""  },
	{ title:"Pioneers of Psychology", author:"Fancher", year:1979, done:false, genre:"psychology", wc:206528, 
		ss:"", sum:""  },
	{ title:"Principles of Psychology", author:"James", year:1890, done:false, genre:"psychology", wc:154375, 
		ss:"", sum:""  },
	{ title:"The Varieties of Religious Experience", author:"James", year:1902, done:true, genre:"psychology", wc:154913, 
		ss:"", sum:""  },
	{ title:"Learning, Memory and Conceptual Processes", author:"Kintsch", year:1970, done:false, genre:"psychology", wc:124500, 
		ss:"", sum:""  },
	// Race and Ethnicity
	{ title:"The New Jim Crow: Mass Incarceration in the Age of Colorblindness", author:"Alexander", year:2010, done:true, genre:"race", wc:94681, 
		ss:"", sum:""  },
	{ title:"Between the World and Me", author:"Coates", year:2015, done:false, genre:"race", wc:44615, 
		ss:"", sum:""  },
	{ title:"White Fragility: Why It's So Hard for White People to Talk About Racism", author:"DiAngelo", year:2018, done:false, genre:"race", wc:51614, 
		ss:"", sum:""  },
	{ title:"Ghosts in the Schoolyard: Racism and School Closings on Chicago's South Side", author:"Ewing", year:2018, done:false, genre:"race", wc:64534, 
		ss:"", sum:""  },
	{ title:"The Making of Asian America", author:"Lee", year:2015, done:true, genre:"race", wc:159961, 
		ss:"", sum:""  },
	{ title:"Politics of the Veil", author:"Scott", year:2007, done:false, genre:"race", wc:60227, 
		ss:"", sum:""  },
	// Sociology and Social Class
	{ title:"Imagined Communities: Reflections on the Origin and Spread of Nationalism", author:"Anderson", year:1983, done:false, genre:"sociology", wc:68841, 
		ss:"", sum:""  },
	{ title:"Modernity at Large: Cultural Dimensions of Globalization", author:"Appadorei", year:1996, done:false, genre:"sociology", wc:66688, 
		ss:"", sum:""  },
	{ title:"The Social Construction of Reality", author:"Berger and Luckmann", year:1966, done:false, genre:"sociology", wc:58882, 
		ss:"", sum:""  },
	{ title:"Suicide: A Study In Sociology", author:"Durkheim", year:1897, done:false, genre:"sociology", wc:111901, 
		ss:"", sum:""  },
	{ title:"Discipline and Punish: The Birth of the Prison", author:"Foucault", year:1975, done:false, genre:"sociology", wc:89567, 
		ss:"", sum:""  },
	{ title:"Pedagogy of the Oppressed", author:"Freire", year:1968, done:true, genre:"sociology", wc:62381, 
		ss:"", sum:""  },
	{ title:"The True Believer: Thoughts on the Nature of Mass Movements", author:"Hoffer", year:1951, done:false, genre:"sociology", wc:51614, 
		ss:"", sum:""  },
	{ title:"The Sociological Imagination", author:"Mills", year:1959, done:false, genre:"sociology", wc:68841, 
		ss:"", sum:""  },
	{ title:"Scarcity: THe New Science of Having Less and How it Defines Our Lives", author:"Mullainathan and Shafir", year:2013, done:false, genre:"sociology", wc:81761, 
		ss:"", sum:""  },
	{ title:"Culture and Imperialism", author:"Said", year:1993, done:false, genre:"sociology", wc:102218, 
		ss:"", sum:""  },
	
	// Other books of personal interest
	{ title:"Plant-Based Sports Nutrition", author:"Larson-Meyer and Ruscigno", year:2019, done:true, genre:"personal", wc:92528, 
		ss:"", sum:""  },
	{ title:"Training Essentials for Ultrarunning", author:"Koop", year:2016, done:true, genre:"personal", wc:94681, 
		ss:"", sum:""  },
	{ title:"Hal Koerner's Field Guide to Ultrarunning", author:"Koerner", year:2014, done:true, genre:"personal", wc:60227, 
		ss:"", sum:""  },
	{ title:"Born to Run", author:"McDougall", year:2009, done:true, genre:"personal", wc:81761, 
		ss:"", sum:""  },
	{ title:"Finding Ultra", author:"Roll", year:2012, done:true, genre:"personal", wc:107599, 
		ss:"", sum:""  },
	{ title:"Eat and Run", author:"Jurek", year:2012, done:true, genre:"personal", wc:77454, 
		ss:"", sum:""  },
	{ title:"Why Only Us: Language and Evolution", author:"Burwick and Chomsky", year:2017, done:true, genre:"personal", wc:60227, 
		ss:"", sum:""  },
];