// Source of the array of books used to create the reading list
var books = [
	// ART
	{ title:"How to Read a Film", author:"Monaco", year:1977, done:false, genre:"film", },
    { title:"The Story of Film: A Worldwide History", author:"Cousins", year:2004, done:false, genre:"film" },
	{ title:"American Cinema: Directors and Directions", author:"Sarris", year:1968, done:false, genre:"film" },
	{ title:"History of the Theater", author:"Brockett", year:1968, done:false, genre:"performing" },
	{ title:"Music: A Very Short Introduction", author:"Cook", year:1998, done:true, genre:"performing" },
	{ title:"Everything You’ve Ever Wanted to Know About Classical Music but Were too Afraid to Ask", author:"Henley and Jackson", year:2012, done:false, genre:"performing" },
	{ title:"The Rest is Noise", author:"Ross", year:2007, done:false, genre:"performing" },
	{ title:"The Gilded Stage: A Social History of Opera", author:"Snowman", year:2009, done:false, genre:"performing" },
	{ title:"A Short Guide to Writing About Art", author:"Barnet", year:1981, done:false, genre:"visual" },
	{ title:"Architecture: A World History", author:"Borden, Elzanowski, and Taylor", year:2008, done:false, genre:"visual" },
	{ title:"Modern Art 1851-1929: Capitalism and Representation", author:"Brettes", year:1999, done:false, genre:"visual" },
	{ title:"Art in Theory 1900-2000", author:"Harrison and Wood", year:1992, done:false, genre:"visual" },
	{ title:"Brunelleschi’s Dome: How a Renaissance Genius Reinvented Architecture", author:"King", year:2000, done:true, genre:"visual" },
	{ title:"The Judgement of Paris: The Revolutionary Decade that Gave the World Impressionism", author:"King", year:2006, done:false, genre:"visual" },
	
	// Prehistory
	{ title:"SPQR", author:"Beard", year:2015, done:true, genre:"prehist" },
	{ title:"Greek History: The Basics", author:"Osbourne", year:2004, done:false, genre:"prehist" },
	{ title:"The Ancient Near East: A Very Short History", author:"Podany", year:2013, done:false, genre:"prehist" },
	{ title:"The Human Past: World Prehistory and the Development of Human Societies", author:"Scarre", year:2005, done:false, genre:"prehist" },
	// World history
	{ title:"Europe: A History", author:"Davies", year:1996, done:true, genre:"worldhist" },
	{ title:"China: A New History", author:"Fairbank", year:1992, done:false, genre:"worldhist" },
	{ title:"Africans: The History of a Continent", author:"Iliffe", year:1995, done:false, genre:"worldhist" },
	{ title:"A History of India", author:"Kulke and Rothermund", year:1986, done:false, genre:"worldhist" },
	{ title:"The Middle East: A Brief History of the Last 2,000 Years", author:"Lewis", year:1995, done:false, genre:"worldhist" },
	{ title:"1491: New Revelations of the Americas Before Columbus", author:"Mann", year:2005, done:false, genre:"worldhist" },
	{ title:"A People's History of the United States", author:"Zinn", year:1980, done:true, genre:"worldhist" },
	// Contemporary History
	{ title:"The Age of Extremes: A History of the World 1914-1991", author:"Hobsbawm", year:1994, done:true, genre:"contemphist" },
	
	// Classical writings
	{ title:"Oresteia Trilogy", author:"Aeschylus", year:"458 BCE", done:false, genre:"classical", rank:{tgb:114} },
	{ title:"Medea", author:"Euripides", year:"431 BCE", done:true, genre:"classical", rank:{tgb:160} },
	{ title:"Histories", author:"Herodotus", year:"c. 430 BCE", done:true, genre:"classical" },
	{ title:"Odyssey", author:"Homer", year:"c. 750 BCE", done:true, genre:"classical", rank:{tgb:9} },
	{ title:"Iliad", author:"Homer", year:"c. 750 BCE", done:true, genre:"classical", rank:{tgb:21} },
	{ title:"Metamorphoses", author:"Ovid", year:"8 CE", done:false, genre:"classical", rank:{tgb:154} },
	{ title:"Enneads", author:"Plotinus", year:"c. 270", done:false, genre:"classical" },
	{ title:"Parallel Lives", author:"Plutarch", year:"c. 100", done:false, genre:"classical" },
	{ title:"Antigone", author:"Sophocles", year:"442 BCE", done:true, genre:"classical", rank:{tgb:66} },
	{ title:"Oedipus at Colonus", author:"Sophocles", year:"401 BCE", done:true, genre:"classical", rank:{tgb:158} },
	{ title:"Oedipus the King", author:"Sophocles", year:"429 BCE", done:true, genre:"classical", rank:{tgb:51} },
	{ title:"Elektra", author:"Sophocles", year:"c. 400 BCE", done:true, genre:"classical", rank:{tgb:205} },
	{ title:"Lives of the Caesars", author:"Suetonius", year:121, done:false, genre:"classical" },
	{ title:"Annals", author:"Tacitus", year:"c. 100", done:false, genre:"classical" },
	{ title:"Epic of Gilgamesh", author:"Unknown", year:"c. 1800 BCE", done:false, genre:"classical", rank:{tgb:136} },
	{ title:"Aeneid", author:"Vergil", year:"c. 29-19 BCE", done:false, genre:"classical", rank:{tgb:42} },
	{ title:"De Rerum Natura", author:"Lucretius", year:"c. 50 BCE", done:false, genre:"classical", rank:{tgb:227} },
	
	// Premodern literature
	{ title:"The Divine Comedy", author:"Alighieri", year:1320, done:true, genre:"premodern", rank:{tgb:11} },
	{ title:"Decameron", author:"Boccacio", year:"c. 1350", done:false, genre:"premodern", rank:{tgb:100} },
	{ title:"Canterbury Tales", author:"Chaucer", year:1392, done:false, genre:"premodern", rank:{tgb:80} },
	{ title:"The Tale of Genji", author:"Shikibu", year:1008, done:false, genre:"premodern", rank:{tgb:128} },
	{ title:"One Thousand and One Nights", author:"Various", year:"c. 900", done:false, genre:"premodern", rank:{tgb:28} },
	{ title:"The Princess of Cleves", author:"La Fayette", year:1678, done:true, genre:"premodern", rank:{tgb:186} },
	
	// Early modern literature
	{ title:"Don Quixote", author:"Cervantes", year:1605, done:true, genre:"early", rank:{tgb:3} },
	{ title:"Dangerous Liaisons", author:"Laclos", year:1782, done:true, genre:"early", rank:{tgb:141} },
	{ title:"Gargantua and Pantagruel", author:"Rabelais", year:1534, done:false, genre:"early", rank:{tgb:95} },
	{ title:"Candide", author:"Voltaire", year:1759, done:true, genre:"early", rank:{tgb:52} },
	{ title:"Robinson Crusoe", author:"Defoe", year:1719, done:false, genre:"early", rank:{tgb:103} },
	{ title:"Gulliver’s Travels", author:"Swift", year:1726, done:true, genre:"early", rank:{tgb:36} },
	{ title:"Tom Jones", author:"Fielding", year:1749, done:false, genre:"early", rank:{tgb:105} },
	{ title:"Tristram Shandy", author:"Sterne", year:1759, done:false, genre:"early", rank:{tgb:46} },
	
	// 19th Century Literature
	{ title:"Pride and Prejudice", author:"Austen", year:1813, done:true, genre:"19th", rank:{tgb:17} },
	{ title:"Emma", author:"Austen", year:1815, done:true, genre:"19th", rank:{tgb:59} },
	{ title:"Cousin Bette", author:"Balzac", year:1846, done:true, genre:"19th", rank:{tgb:126} },
	{ title:"Eugenie Grandet", author:"Balzac", year:1833, done:false, genre:"19th", rank:{tgb:180} },
	{ title:"Father Goriot", author:"Balzac", year:1834, done:false, genre:"19th", rank:{tgb:109} },
	{ title:"Lost Illusions", author:"Balzac", year:1837, done:false, genre:"19th", rank:{tgb:162} },
	{ title:"Jane Eyre", author:"C. Bronte", year:1847, done:true, genre:"19th", rank:{tgb:41} },
	{ title:"Wuthering Heights", author:"E. Bronte", year:1847, done:true, genre:"19th", rank:{tgb:15} },
	{ title:"Bleak House", author:"Dickens", year:1852, done:true, genre:"19th", rank:{tgb:116} },
	{ title:"David Copperfield", author:"Dickens", year:1850, done:true, genre:"19th", rank:{tgb:45} },
	{ title:"Great Expectations", author:"Dickens", year:1860, done:false, genre:"19th", rank:{tgb:27} },
	{ title:"The Pickwick Papers", author:"Dickens", year:1836, done:true, genre:"19th", rank:{tgb:190} },
	{ title:"A Tale of Two Cities", author:"Dickens", year:1859, done:true, genre:"personal", rank:{tgb:231} },
	{ title:"The Brothers Karamazov", author:"Dostoyevsky", year:1880, done:true, genre:"19th", rank:{tgb:13} },
	{ title:"Crime and Punishment", author:"Dostoyevsky", year:1866, done:true, genre:"19th", rank:{tgb:14} },
	{ title:"The Idiot", author:"Dostoyevsky", year:1869, done:true, genre:"19th", rank:{tgb:54} },
	{ title:"The Possessed", author:"Dostoyevsky", year:1871, done:false, genre:"19th", rank:{tgb:69} },
	{ title:"The Count of Monte Cristo", author:"Dumas", year:1844, done:true, genre:"19th", rank:{tgb:135} },
	{ title:"The Three Musketeers", author:"Dumas", year:1844, done:true, genre:"personal", rank:{tgb:222} },
	{ title:"Middlemarch", author:"Eliot", year:1871, done:true, genre:"19th", rank:{tgb:35} },
	{ title:"Madame Bovary", author:"Flaubert", year:1856, done:true, genre:"19th", rank:{tgb:10} },
	{ title:"A Sentimental Education", author:"Flaubert", year:1869, done:false, genre:"19th", rank:{tgb:87} },
	{ title:"Dead Souls", author:"Gogol", year:1842, done:true, genre:"19th", rank:{tgb:75} },
	{ title:"Tess of the d’Urbervilles", author:"Hardy", year:1891, done:false, genre:"19th", rank:{tgb:101} },
	{ title:"Jude the Obscure", author:"Hardy", year:1895, done:false, genre:"19th", rank:{tgb:194} },
	{ title:"The Scarlet Letter", author:"Hawthorne", year:1850, done:true, genre:"19th", rank:{tgb:88} },
	{ title:"Les Miserables", author:"Hugo", year:1862, done:false, genre:"19th", rank:{tgb:55} },
	{ title:"Moby-Dick; or, The Whale", author:"Melville", year:1851, done:true, genre:"19th", rank:{tgb:6} },
	{ title:"The Complete Tales of Edgar Allen Poe", author:"Poe", year:1846, done:false, genre:"19th", rank:{tgb:73} },
	{ title:"The Red and the Black", author:"Stendhal", year:1830, done:true, genre:"19th", rank:{tgb:34} },
	{ title:"The Charterhouse of Parma", author:"Stendhal", year:1839, done:false, genre:"19th", rank:{tgb:93} },
	// { title:"Uncle Tom’s Cabin", author:"Stowe", year:1852, done:false, genre:"personal", rank:{tgb:416} },
	{ title:"Vanity Fair", author:"Thackeray", year:1847, done:false, genre:"19th", rank:{tgb:81} },
	{ title:"Anna Karenina", author:"Tolstoy", year:1877, done:true, genre:"19th", rank:{tgb:19} },
	{ title:"War and Peace", author:"Tolstoy", year:1867, done:true, genre:"19th", rank:{tgb:7} },
	{ title:"Fathers and Sons", author:"Turgenev", year:1862, done:true, genre:"19th", rank:{tgb:113} },
	{ title:"The Adventures of Huckleberry Finn", author:"Twain", year:1884, done:true, genre:"19th", rank:{tgb:18} },
	{ title:"Picture of Dorian Gray", author:"Wilde", year:1890, done:true, genre:"personal", rank:{tgb:206} },
	{ title:"Portrait of a Lady", author:"James", year:1881, done:false, genre:"19th", rank:{tgb:63} },
	{ title:"The Ambassadors", author:"James", year:1903, done:false, genre:"19th", rank:{tgb:167} },
	
	// 20th Century Literature
	{ title:"The Master and Margarita", author:"Bulgakov", year:1966, done:true, genre:"20th", rank:{tgb:108} },
	{ title:"The Stories of Anton Chekhov", author:"Chekhov", year:1932, done:false, genre:"20th", rank:{tgb:39} },
	{ title:"Rebecca", author:"du Maurier", year:1938, done:false, genre:"20th", rank:{tgb:98} },
	{ title:"My Antonia", author:"Cather", year:1918, done:false, genre:"20th", rank:{tgb:145} },
	{ title:"Heart of Darkness", author:"Conrad", year:1902, done:true, genre:"20th", rank:{tgb:24} },
	{ title:"Nostromo", author:"Conrad", year:1904, done:false, genre:"20th", rank:{tgb:138} },
	{ title:"Lord Jim", author:"Conrad", year:1900, done:true, genre:"20th", rank:{tgb:123} },
	{ title:"The Sound and the Fury", author:"Falkner", year:1929, done:false, genre:"20th", rank:{tgb:25} },
	{ title:"As I Lay Dying", author:"Falkner", year:1930, done:true, genre:"20th", rank:{tgb:67} },
	{ title:"Absalom, Absalom!", author:"Falkner", year:1936, done:true, genre:"20th", rank:{tgb:30} },
	{ title:"The Great Gatsby", author:"Fitzgerald", year:1925, done:true, genre:"20th", rank:{tgb:5} },
	{ title:"Tender Is the Night", author:"Fitzgerald", year:1934, done:true, genre:"20th", rank:{tgb:149} },
	{ title:"The Good Soldier", author:"Ford", year:1915, done:false, genre:"20th", rank:{tgb:77} },
	{ title:"A Passage to India", author:"Forster", year:1924, done:true, genre:"20th", rank:{tgb:56} },
	{ title:"Howard’s End", author:"Forster", year:1910, done:false, genre:"20th", rank:{tgb:118} },
	{ title:"A Room with a View", author:"Forster", year:1908, done:false, genre:"20th", rank:{tgb:181} },
	{ title:"Invisible Man", author:"Ellison", year:1952, done:false, genre:"20th", rank:{tgb:31} },
	{ title:"The Sun Also Rises", author:"Hemingway", year:1926, done:true, genre:"20th", rank:{tgb:44} },
	{ title:"Stories of Ernest Hemingway", author:"Hemingway", year:1938, done:true, genre:"20th", rank:{tgb:137} },
	{ title:"The Old Man and the Sea", author:"Hemingway", year:1952, done:true, genre:"20th", rank:{tgb:57} },
	{ title:"For Whom the Bell Tolls", author:"Hemingway", year:1940, done:true, genre:"20th", rank:{tgb:60} },
	{ title:"A Farewell to Arms", author:"Hemingway", year:1929, done:false, genre:"20th", rank:{tgb:84} },
	{ title:"A Portrait of the Artist as a Young Man", author:"Joyce", year:1916, done:true, genre:"20th", rank:{tgb:49} },
	{ title:"Ulysses", author:"Joyce", year:1922, done:false, genre:"20th", rank:{tgb:2} },
	{ title:"Dubliners", author:"Joyce", year:1914, done:false, genre:"personal", rank:{tgb:243} },
	{ title:"The Golden Notebook", author:"Lessing", year:1962, done:false, genre:"20th", rank:{tgb:129} },
	{ title:"Call of the Wild", author:"London", year:1903, done:true, genre:"20th", rank:{tgb:148} },
	{ title:"Gone With the Wind", author:"Mitchell", year:1936, done:false, genre:"20th", rank:{tgb:70} },
	{ title:"In Search of Lost Time", author:"Proust", year:1913, done:true, genre:"20th", rank:{tgb:1} },
	{ title:"The Grapes of Wrath", author:"Steinbeck", year:1939, done:true, genre:"20th", rank:{tgb:29} },
	{ title:"East of Eden", author:"Steinbeck", year:1952, done:true, genre:"personal" },
	{ title:"Of Mice and Men", author:"Steinbeck", year:1937, done:true, genre:"20th", rank:{tgb:173} },
	{ title:"The Age of Innocence", author:"Wharton", year:1920, done:true, genre:"20th", rank:{tgb:74} },
	{ title:"The House of Mirth", author:"Wharton", year:1905, done:true, genre:"20th", rank:{tgb:199} },
	{ title:"Things Fall Apart", author:"Achebe", year:1958, done:true, genre:"20th", rank:{tgb:58} },
	{ title:"Collected Fiction", author:"Borges", year:1944, done:true, genre:"20th", rank:{tgb:43} },
	{ title:"The Stranger", author:"Camus", year:1942, done:true, genre:"20th", rank:{tgb:40} },
	{ title:"The Plague", author:"Camus", year:1947, done:false, genre:"20th", rank:{tgb:188} },
	{ title:"Journey to the End of the Night", author:"Celine", year:1932, done:false, genre:"20th", rank:{tgb:85} },
	{ title:"The Tin Drum", author:"Grass", year:1959, done:true, genre:"20th", rank:{tgb:110} },
	{ title:"The Quiet American", author:"Greene", year:1955, done:true, genre:"personal", rank:{tgb:470} },
	{ title:"Lord of the Flies", author:"Golding", year:1954, done:true, genre:"20th", rank:{tgb:71} },
	{ title:"Catch-22", author:"Heller", year:1953, done:true, genre:"20th", rank:{tgb:23} },
	{ title:"Their Eyes Were Watching God", author:"Hurston", year:1937, done:true, genre:"20th", rank:{tgb:104} },
	{ title:"The Complete Stories of Franz Kafka", author:"Kafka", year:1971, done:true, genre:"20th", rank:{tgb:61} },
	{ title:"The Castle", author:"Kafka", year:1926, done:true, genre:"20th", rank:{tgb:86} },
	{ title:"The Metamorphosis", author:"Kafka", year:1915, done:true, genre:"20th", rank:{tgb:61} },
	{ title:"The Trial", author:"Kafka", year:1925, done:true, genre:"20th", rank:{tgb:33} },
	{ title:"On the Road", author:"Kerouac", year:1957, done:true, genre:"20th", rank:{tgb:76} },
	{ title:"One Flew Over the Cuckoo's Nest", author:"Kesey", year:1962, done:false, genre:"20th", rank:{tgb:152} },
	{ title:"Sons and Lovers", author:"Lawrence", year:1913, done:false, genre:"20th", rank:{tgb:111} },
	// { title:"The Rainbow", author:"Lawrence", year:1915, done:false, genre:"personal", rank:{tgb:350} },
	{ title:"Women in Love", author:"Lawrence", year:1920, done:false, genre:"20th", rank:{tgb:172} },
	{ title:"To Kill a Mockingbird", author:"Lee", year:1960, done:true, genre:"20th", rank:{tgb:32} },
	{ title:"Under the Volcano", author:"Lowry", year:1947, done:false, genre:"20th", rank:{tgb:82} },
	{ title:"Buddenbrooks", author:"Mann", year:1901, done:true, genre:"20th", rank:{tgb:144} },
	{ title:"Doctor Faustus", author:"Mann", year:1947, done:true, genre:"20th", rank:{tgb:134} },
	// { title:"The Magic Mountain", author:"Mann", year:1924, done:false, genre:"personal" },
	{ title:"One Hundred Years of Solitude", author:"Marquez", year:1967, done:true, genre:"20th", rank:{tgb:4} },
	{ title:"The Man Without Qualities", author:"Musil", year:1943, done:false, genre:"20th", rank:{tgb:133} },
	{ title:"Lolita", author:"Nabokov", year:1955, done:true, genre:"20th", rank:{tgb:12} },
	{ title:"Pale Fire", author:"Nabokov", year:1962, done:true, genre:"20th", rank:{tgb:65} },
	{ title:"The Complete Stories of Flannery O’Connor", author:"O’Connor", year:1971, done:false, genre:"20th", rank:{tgb:121} },
	{ title:"The Bell Jar", author:"Plath", year:1963, done:true, genre:"personal", rank:{tgb:261} },
	{ title:"All Quiet on the Western Front", author:"Remarque", year:1929, done:true, genre:"20th", rank:{tgb:142} },
	{ title:"Wide Sargasso Sea", author:"Rhys", year:1966, done:true, genre:"20th", rank:{tgb:115} },
	{ title:"The Catcher in the Rye", author:"Salinger", year:1951, done:true, genre:"20th", rank:{tgb:16} },
	{ title:"Rabbit, Run", author:"Updike", year:1960, done:false, genre:"20th", rank:{tgb:122} },
	{ title:"Rabbit Redux", author:"Updike", year:1971, done:false, genre:"20th", rank:{tgb:176} },
	{ title:"Rabbit is Rich", author:"Updike", year:1981, done:false, genre:"20th", rank:{tgb:153} },
	{ title:"Rabbit at Rest", author:"Updike", year:1990, done:false, genre:"personal", rank:{tgb:217} },
	{ title:"Brideshead Revisited", author:"Waugh", year:1945, done:true, genre:"personal", rank:{tgb:274} },
	// { title:"Scoop", author:"Waugh", year:1938, done:false, genre:"personal", rank:{tgb:463} },
	{ title:"All the King's Men", author:"Warren", year:1946, done:false, genre:"20th", rank:{tgb:132} },
	{ title:"To the Lighthouse", author:"Woolf", year:1927, done:true, genre:"20th", rank:{tgb:22} },
	{ title:"Orlando: A Biography", author:"Woolf", year:1928, done:false, genre:"20th", rank:{tgb:79} },
	{ title:"Mrs. Dalloway", author:"Woolf", year:1925, done:true, genre:"20th", rank:{tgb:38} },
	{ title:"The Waves", author:"Woolf", year:1931, done:false, genre:"20th", rank:{tgb:175} },
	{ title:"Native Son", author:"Wright", year:1940, done:false, genre:"20th", rank:{tgb:92} },
	{ title:"Nineteen Eighty-Four", author:"Orwell", year:0, done:true, genre:"20th", rank:{tgb:26} },
	{ title:"Animal Farm", author:"Orwell", year:0, done:true, genre:"20th", rank:{tgb:78} },
	{ title:"Fear and Loathing in Las Vegas", author:"Thompson", year:1971, done:false, genre:"20th", rank:{tgb:130} },
	
	{ title:"The Moviegoer", author:"Percy", year:1961, done:false, genre:"20th", rank:{tgb:159} },
	{ title:"Pedro Paramo", author:"Rulfo", year:1955, done:false, genre:"20th", rank:{tgb:163} },
	{ title:"The Prime of Miss Jean Brodie", author:"Spark", year:1961, done:false, genre:"20th", rank:{tgb:164} },
	{ title:"Doctor Zhivago", author:"Pasternak", year:1957, done:false, genre:"20th", rank:{tgb:166}},
	{ title:"Confessions of Zeno", author:"Svevo", year:1923, done:false, genre:"20th", rank:{tgb:170}},
	{ title:"The Leopard", author:"Lampedusa", year:1958, done:false, genre:"20th", rank:{tgb:178}},
	{ title:"The Stories of John Cheever", author:"Cheever", year:1978, done:false, genre:"20th", rank:{tgb:191}},
	{ title:"The 42nd Parallel", author:"Dos Passos", year:1930, done:false, genre:"20th", rank:{tgb:196}},
	{ title:"Nineteen Nineteen", author:"Dos Passos", year:1932, done:false, genre:"20th", rank:{tgb:195}},
	{ title:"The Big Money", author:"Dos Passos", year:1936, done:false, genre:"20th", rank:{tgb:197}},
	{ title:"Independent People", author:"Laxness", year:1946, done:false, genre:"20th", rank:{tgb:198}},
	{ title:"The Jungle", author:"Sinclair", year:1906, done:true, genre:"personal", rank:{tgb:234}},
	{ title:"Gravity's Rainbow", author:"Pynchon", year:1973, done:false, genre:"personal", rank:{tgb:242}},
	{ title:"Steppenwolf", author:"Hesse", year:1927, done:false, genre:"personal", rank:{tgb:246}},
	{ title:"Siddhartha", author:"Hesse", year:1922, done:true, genre:"personal", rank:{tgb:266}},
	
	// 21st Century Literature
	{ title:"Beloved", author:"Morrison", year:1987, done:true, genre:"21st", rank:{tgb:37} },
	{ title:"Song of Solomon", author:"Morrison", year:1977, done:true, genre:"personal", rank:{tgb:239} },
	{ title:"White Teeth", author:"Smith", year:2000, done:false, genre:"21st", rank:{tgb:127} },
	{ title:"Love in the Time of Cholera", author:"Marquez", year:1985, done:true, genre:"21st", rank:{tgb:143} },
	{ title:"Americanah", author:"Adichie", year:2013, done:false, genre:"personal" },
	{ title:"If on a Winter’s Night a Traveller", author:"Calvino", year:1979, done:false, genre:"personal", rank:{tgb:225} },
	{ title:"The Brief Wondrous Life of Oscar Wao", author:"Diaz", year:2007, done:false, genre:"21st", rank:{tgb:156} },
	{ title:"The Corrections", author:"Franzen", year:2001, done:false, genre:"21st", rank:{tgb:147} },
	{ title:"Remains of the Day", author:"Ishiguro", year:1989, done:false, genre:"21st", rank:{tgb:168} },
	{ title:"The Unbearable Lightness of Being", author:"Kundera", year:1984, done:true, genre:"personal", rank:{tgb:256} },
	{ title:"Atonement", author:"McEwan", year:2001, done:false, genre:"21st", rank:{tgb:125} },
	{ title:"The Wind-Up Bird Chronicles", author:"Murakami", year:1994, done:true, genre:"21st", rank:{tgb:187} },
	{ title:"Midnight’s Children", author:"Rushdie", year:1981, done:false, genre:"21st", rank:{tgb:50} },
	{ title:"Confederacy of Dunces", author:"Toole", year:1980, done:false, genre:"21st", rank:{tgb:124} },
	{ title:"The Color Purple", author:"Walker", year:1982, done:false, genre:"21st", rank:{tgb:68} },
	{ title:"On Earth We're Briefly Gorgeous", author:"Vuong", year:2019, done:true, genre:"personal" },
	
	
	{ title:"A Prayer for Owen Meany", author:"Irving", year:1989, done:false, genre:"21st", rank:{tgb:151}},
	{ title:"The World According to Garp", author:"Irving", year:1978, done:false, genre:"21st", rank:{tgb:200}},
	{ title:"Austerlitz", author:"Sebald", year:2001, done:false, genre:"21st", rank:{tgb:169}},
	{ title:"2666", author:"Bolaño", year:2004, done:false, genre:"21st", rank:{tgb:179}},
	{ title:"The Sea, The Sea", author:"Murdoch", year:1978, done:false, genre:"21st", rank:{tgb:182}},
	{ title:"The Bonfire of the Vanities", author:"Wolfe", year:1987, done:false, genre:"21st", rank:{tgb:183}},
	{ title:"The House of the Spirits", author:"Allende", year:1982, done:false, genre:"21st", rank:{tgb:184}},
	{ title:"The Amazing Adventures of Kavalier and Clay", author:"Chabon", year:2000, done:true, genre:"personal", rank:{tgb:229} },
	
	// Biography and Memoir
	{ title:"I Know Why the Caged Bird Sings", author:"Angelou", year:1969, done:true, genre:"biography" },
	{ title:"Borderlands/La Frontera: The New Mestiza", author:"Anzaldua", year:1987, done:false, genre:"biography" },
	{ title:"Confessions", author:"Augustine", year:397, done:false, genre:"biography" },
	{ title:"Alexander Hamilton", author:"Chernow", year:2004, done:true, genre:"biography" },
	{ title:"A Year of Magical Thinking", author:"Didion", year:2005, done:true, genre:"biography" },
	{ title:"Narrative of the Life of Frederick Douglass", author:"Douglass", year:1845, done:true, genre:"biography" },
	{ title:"Nickel and Dimed", author:"Ehrenreich", year:2001, done:true, genre:"biography" },
	{ title:"Diary of a Young Girl", author:"Frank", year:1947, done:true, genre:"biography" },
	{ title:"The Autobiography of Malcolm X", author:"Haley", year:1965, done:true, genre:"biography" },
	{ title:"Alan Turing: The Enigma", author:"Hodges", year:1983, done:true, genre:"biography" },
	{ title:"When Breath Becomes Air", author:"Kalanithi", year:2016, done:true, genre:"biography" },
	{ title:"My First Summer in the Sierra", author:"Muir", year:1911, done:true, genre:"biography" },
	{ title:"Speak, Memory", author:"Nabokov", year:1951, done:true, genre:"biography" },
	{ title:"Dreams from my Father", author:"Obama", year:1995, done:true, genre:"biography" },
	{ title:"Confessions", author:"Rousseau", year:1782, done:false, genre:"biography" },
	{ title:"Up From Slavery", author:"Washington", year:1901, done:true, genre:"biography" },
	{ title:"The Double Helix", author:"Watson", year:1968, done:true, genre:"biography" },
	{ title:"Hillbilly Elegy", author:"Vance", year:2016, done:true, genre:"biography" },
	
	// Children's Literature
	{ title:"Little Women", author:"Alcott", year:1868, done:false, genre:"children", rank:{tgb:119} },
	{ title:"Fairy Tales and Stories", author:"Anderson", year:1837, done:true, genre:"children", rank:{tgb:120} },
	{ title:"Charlotte's Web", author:"White", year:1952, done:true, genre:"children", rank:{tgb:91} },
	{ title:"Alice's Adventures in Wonderland", author:"Carroll", year:1865, done:true, genre:"children", rank:{tgb:20} },
	{ title:"Through the Looking Glass", author:"Carroll", year:1871, done:true, genre:"children", rank:{tgb:249} },
	{ title:"The Wind in the Willows", author:"Grahame", year:1908, done:true, genre:"children", rank:{tgb:150} },
	{ title:"Treasure Island", author:"Stevenson", year:1883, done:false, genre:"children", rank:{tgb:131} },
	{ title:"The Little Prince", author:"Saint-Exupery", year:1943, done:false, genre:"children", rank:{tgb:112} },
	{ title:"His Dark Materials", author:"Pullman", year:1997, done:true, genre:"personal", rank:{tgb:413} },
	{ title:"Harry Potter", author:"Rowling", year:1997, done:true, genre:"children", rank:{tgb:209} },
	
	{ title:"The Lion, the Witch and the Wardrobe", author:"Lewis", year:1950, done:true, genre:"children", rank:{tgb:157} },
	{ title:"A Tree Grows in Brooklyn", author:"Smith", year:1943, done:false, genre:"children", rank:{tgb:165} },
	{ title:"Winnie the Pooh", author:"Milne", year:1926, done:false, genre:"children", rank:{tgb:214} },
	
	// Commentary
	{ title:"Notes of a Native Son", author:"Baldwin", year:1955, done:true, genre:"commentary" },
	{ title:"The Fire Next Time", author:"Baldwin", year:1963, done:false, genre:"commentary" },
	{ title:"Slouching Toward Bethlehem", author:"Didion", year:1968, done:false, genre:"commentary" },
	{ title:"Writings of Emerson", author:"Emerson", year:1885, done:true, genre:"commentary" },
	{ title:"Being Mortal", author:"Gawande", year:2014, done:true, genre:"commentary" },
	{ title:"Essays", author:"Montaigne", year:1580, done:true, genre:"commentary" },
	{ title:"How to Do Nothing: Resisting the Attention Economy", author:"Odell", year:2019, done:true, genre:"personal" },
	{ title:"Essays of George Orwell", author:"Orwell", year:1970, done:false, genre:"commentary" },
	{ title:"Pensees", author:"Pascal", year:1670, done:false, genre:"commentary" },
	{ title:"Against Interpretation", author:"Sontag", year:1966, done:false, genre:"commentary" },
	{ title:"Walden, or Life in the Woods", author:"Thoreau", year:1854, done:true, genre:"commentary" },
	{ title:"A Room of One’s Own", author:"Woolf", year:1929, done:true, genre:"commentary" },
	
	// Drama
	{ title:"Who's Afraid of Virginia Woolf?", author:"Albee", year:1962, done:false, genre:"drama" },
	{ title:"Waiting for Godot", author:"Beckett", year:1953, done:true, genre:"drama", rank:{tgb:102} },
	{ title:"Faust", author:"Goethe", year:1829, done:false, genre:"drama", rank:{tgb:97} },
	{ title:"A Raisin in the Sun", author:"Hansberry", year:1959, done:true, genre:"drama" },
	{ title:"A Doll’s House", author:"Ibsen", year:1879, done:true, genre:"drama", rank:{tgb:216} },
	{ title:"Peer Gynt", author:"Ibsen", year:1876, done:true, genre:"drama" },
	{ title:"Angels In America", author:"Kushner", year:1991, done:true, genre:"drama" },
	{ title:"The Crucible", author:"Miller", year:1953, done:true, genre:"drama" },
	{ title:"Death of a Salesman", author:"Miller", year:1949, done:true, genre:"drama" },
	{ title:"Tartuffe", author:"Moliere", year:1664, done:true, genre:"drama" },
	{ title:"Long Day's Journey Into Night", author:"O'Neill", year:1956, done:true, genre:"drama" },
	{ title:"The Iceman Cometh", author:"O'Neill", year:1946, done:true, genre:"drama" },
	{ title:"Hamlet", author:"Shakespeare", year:1609, done:true, genre:"drama", rank:{tgb:8} },
	{ title:"King Lear", author:"Shakespeare", year:1606, done:true, genre:"drama", rank:{tgb:106} },
	{ title:"Macbeth", author:"Shakespeare", year:1606, done:true, genre:"drama", rank:{tgb:161} },
	{ title:"A Midsummer Night's Dream", author:"Shakespeare", year:1605, done:true, genre:"drama", rank:{tgb:498} },
	{ title:"Othello", author:"Shakespeare", year:1604, done:true, genre:"drama", rank:{tgb:494} },
	{ title:"The Tempest", author:"Shakespeare", year:1611, done:true, genre:"drama", rank:{tgb:140} },
	{ title:"A Streetcar Named Desire", author:"Williams", year:1947, done:true, genre:"drama" },
	{ title:"The Glass Menagerie", author:"Williams", year:1945, done:true, genre:"drama" },
	
	// Genre fiction
	{ title:"The Hitchhiker’s Guide to the Galaxy", author:"Adams", year:1981, done:true, genre:"genre", rank:{tgb:207} },
	{ title:"The Handmaid’s Tale", author:"Atwood", year:1985, done:true, genre:"genre", rank:{tgb:90} },
	{ title:"Foundation", author:"Asimov", year:1942, done:true, genre:"personal", rank:{tgb:379} },
	{ title:"Clockwork Orange", author:"Burgess", year:1962, done:true, genre:"genre", rank:{tgb:107} },
	{ title:"The Big Sleep", author:"Chandler", year:1939, done:true, genre:"genre", rank:{tgb:139} },
	{ title:"Do Androids Dream of Electric Sheep", author:"Dick", year:1968, done:true, genre:"personal", rank:{tgb:422} },
	{ title:"Neuromancer", author:"Gibson", year:1984, done:true, genre:"personal", rank:{tgb:400} },
	{ title:"Dune", author:"Herbert", year:1965, done:true, genre:"genre", rank:{tgb:220} },
	{ title:"Brave New World", author:"Huxley", year:1932, done:true, genre:"genre", rank:{tgb:72} },
	{ title:"Blood Meridian", author:"McCarthy", year:1985, done:true, genre:"genre", rank:{tgb:146} },
	{ title:"The Road", author:"McCarthy", year:2006, done:true, genre:"genre", rank:{tgb:224} },
	{ title:"Frankenstein", author:"Shelley", year:1823, done:true, genre:"genre", rank:{tgb:64} },
	{ title:"The Strange Case of Dr. Jekyll and Mr. Hyde", author:"Stevenson", year:1886, done:false, genre:"genre", rank:{tgb:189} },
	{ title:"Dracula", author:"Stoker", year:1897, done:true, genre:"genre", rank:{tgb:171} },
	{ title:"Lord of the Rings", author:"Tolkien", year:1954, done:true, genre:"genre", rank:{tgb:53} },
	{ title:"The Hobbit", author:"Tolkien", year:1937, done:true, genre:"genre", rank:{tgb:193} },
	{ title:"Twenty Thousand Leagues Under the Sea", author:"Verne", year:1870, done:true, genre:"genre", rank:{tgb:185} },
	{ title:"Slaughterhouse-Five", author:"Vonnegut", year:1969, done:true, genre:"genre", rank:{tgb:89} },
	{ title:"The Time Machine", author:"Wells", year:1895, done:true, genre:"genre", rank:{tgb:237} },
	
	{ title:"The Complete Sherlock Holmes", author:"Doyle", year:1892, done:true, genre:"genre", rank:{tgb:174} },
	{ title:"Hound of the Baskervilles", author:"Doyle", year:1902, done:true, genre:"genre", rank:{tgb:177} },
	{ title:"Fahrenheit 451", author:"Bradbury", year:1953, done:true, genre:"genre", rank:{tgb:192} },
	{ title:"Stranger in a Strange Land", author:"Heinlein", year:1961, done:true, genre:"genre", rank:{tgb:213} },
	{ title:"2001: A Space Odyssey", author:"Clarke", year:1968, done:false, genre:"personal", rank:{tgb:258} },
	
	// Historical narrative
	{ title:"Bury My Heart at Wounded Knee", author:"Brown", year:1970, done:false, genre:"historical" },
	{ title:"In Cold Blood", author:"Capote", year:1965, done:true, genre:"historical" },
	{ title:"Black Reconstruction in America", author:"DuBois", year:1935, done:false, genre:"historical" },
	{ title:"Hiroshima", author:"Hersey", year:1946, done:false, genre:"historical" },
	{ title:"The Death and Life of Great American Cities", author:"Jacobs", year:1961, done:false, genre:"historical" },
	{ title:"Modern Times", author:"Johnson", year:1983, done:false, genre:"historical" },
	{ title:"This Radical Land", author:"Miller", year:2018, done:true, genre:"historical" },
	{ title:"Making of the Atomic Bomb", author:"Rhodes", year:1986, done:true, genre:"historical" },
	{ title:"And the Band Played On", author:"Skilts and Greider", year:1987, done:false, genre:"historical" },
	{ title:"Working", author:"Terkel", year:1974, done:false, genre:"historical" },
	// Literary criticism, rhetoric and style
	{ title:"Selected Essays of T.S. Eliot", author:"Eliot", year:1932, done:false, genre:"criticism" },
	{ title:"Aspects of the Novel", author:"Forster", year:1927, done:true, genre:"criticism" },
	{ title:"The Great Tradition", author:"Lewis", year:1948, done:false, genre:"criticism" },
	{ title:"Elements of Style", author:"Strunk and White", year:1918, done:true, genre:"criticism" },
	// Poetry
	{ title:"The Flowers of Evil", author:"Baudelaire", year:1857, done:false, genre:"poetry", rank:{tgb:99} },
	{ title:"Poems of Emily Dickinson", author:"Dickinson", year:1890, done:true, genre:"poetry", rank:{tgb:96} },
	{ title:"The Waste Land", author:"Eliot", year:1922, done:true, genre:"poetry", rank:{tgb:83} },
	{ title:"Poems of Robert Frost", author:"Frost", year:1962, done:true, genre:"poetry", rank:{tgb:236} },
	{ title:"Howl", author:"Ginsberg", year:1956, done:true, genre:"personal" },
	{ title:"Paradise Lost", author:"Milton", year:1667, done:true, genre:"poetry", rank:{tgb:94} },
	{ title:"A Season in Hell", author:"Rimbaud", year:1873, done:true, genre:"poetry", rank:{tgb:117} },
	{ title:"Poems of Alfred Tennyson", author:"Tennyson", year:1898, done:false, genre:"personal" },
	{ title:"Leaves of Grass", author:"Whitman", year:1855, done:true, genre:"poetry", rank:{tgb:48} },
	{ title:"Poems of W.B. Yeats", author:"Yeats", year:1940, done:false, genre:"poetry", rank:{tgb:155} },
	
	// Wisdom Literature
	{ title:"Meditations", author:"Aurelius", year:180, done:false, genre:"wisdom" },
	{ title:"The Quran", author:"Muhammad", year:610, done:false, genre:"wisdom" },
	{ title:"Bhagavad-Gita: The Song of God", author:"Various", year:"c. 200 BCE", done:true, genre:"wisdom" },
	{ title:"The Pentateuch", author:"Various", year:"c. 1000 BCE", done:false, genre:"wisdom" },
	{ title:"The Book of Job", author:"Various", year:"c. 500 CE", done:true, genre:"wisdom" },
	{ title:"The New Testament", author:"Various", year:"c. 100", done:false, genre:"wisdom" },
	
	// Applied Science
	{ title:"The Intelligent Investor", author:"Graham", year:1949, done:false, genre:"business" },
	{ title:"Making the Most of Your Money Now", author:"Quinn", year:1991, done:true, genre:"business" },
	{ title:"How to Win Friends and Influence People", author:"Carnegie", year:1936, done:true, genre:"communications" },
	{ title:"Influence", author:"Cialdini", year:1984, done:false, genre:"communications" },
	{ title:"Norton History of Technology", author:"Cardwell", year:1994, done:false, genre:"engineering" },
	{ title:"The Emperor of All Maladies", author:"Mukherjee", year:2010, done:true, genre:"medicine" },
	{ title:"The Greatest Benefit to Mankind: A Medical History of Humanity", author:"Porter", year:1997, done:false, genre:"medicine" },
	{ title:"The Codex", author:"Alexander", year:2017, done:false, genre:"rationality" },
	{ title:"The Most Good You Can Do", author:"Singer", year:2015, done:false, genre:"personal" },
	{ title:"80,000 Hours", author:"Todd", year:2016, done:false, genre:"personal" },
	{ title:"Rationality: A-Z", author:"Yudkowsky", year:2017, done:false, genre:"rationality" },
	{ title:"What You Should Know About Politics… But Don’t", author:"Conrad", year:2008, done:false, genre:"policy" },
	{ title:"Are Prisons Obsolete?", author:"Davis", year:2003, done:false, genre:"policy" },
	{ title:"Law 101", author:"Feinman", year:2000, done:true, genre:"policy" },
	{ title:"The Everything American Government Book", author:"Ragone", year:2004, done:false, genre:"policy" },
	{ title:"Superintelligence: Paths, Dangers, Strategies", author:"Bostrom", year:2014, done:false, genre:"policy" },
	{ title:"Managing Your Mind", author:"Butler", year:1995, done:false, genre:"psychiatry" },
	{ title:"The Portable Jung", author:"Jung", year:1976, done:false, genre:"psychiatry" },
	{ title:"The Freud Reader", author:"Freud", year:1989, done:false, genre:"psychiatry" },
	{ title:"On Becoming a Person", author:"Rogers", year:1956, done:false, genre:"psychiatry" },
	
	// Formal Science
	{ title:"Computer: A History of the Information Machine", author:"Campbell-Kelly and Aspray", year:1996, done:false, genre:"computer" },
	{ title:"The Ethical Algorithm", author:"Roth", year:2019, done:false, genre:"personal" },
	{ title:"Proofs from THE BOOK. (Number Theory, Combinatorics, Graph Theory)", author:"Aigner and Zeigler", year:1998, done:false, genre:"personal" },
	{ title:"The Princeton Companion to Mathematics", author:"Gowers", year:2008, done:false, genre:"math" },
	{ title:"The Norton History of the Mathematical Sciences", author:"Grattan-Guinness", year:1997, done:false, genre:"math" },
	{ title:"Remarkable Mathematicians: From Euler to von Neumann", author:"James", year:2002, done:true, genre:"math" },
	{ title:"A Concise History of Mathematics", author:"Struik", year:1948, done:true, genre:"math" },
	{ title:"Pragmatism", author:"James", year:1907, done:true, genre:"philosophy" },
	{ title:"The Republic", author:"Plato", year:"c. 380 BCE", done:true, genre:"philosophy", rank:{tgb:201} },
	// Natural Science
	{ title:"The Structure of Scientific Revolutions", author:"Kuhn", year:1962, done:true, genre:"natural" },
	{ title:"Coming of Age in the Milky Way", author:"Ferris", year:1988, done:true, genre:"astronomy" },
	{ title:"The Norton History of Astronomy and Cosmology", author:"North", year:1994, done:false, genre:"astronomy" },
	{ title:"On the Origin of Species", author:"Darwin", year:1859, done:true, genre:"biology" },
	{ title:"The Selfish Gene", author:"Dawkins", year:1976, done:true, genre:"biology" },
	{ title:"Life on a Young Planet: The First Three Billion Years of Evolution on Earth", author:"Knoll", year:2003, done:false, genre:"biology" },
	{ title:"What is Life?", author:"Schrodinger", year:1944, done:false, genre:"biology" },
	{ title:"The Epic History of Biology", author:"Serafini", year:1993, done:false, genre:"biology" },
	{ title:"Lives of a Cell", author:"Thomas", year:1974, done:true, genre:"biology" },
	{ title:"The Norton History of Chemistry", author:"Brock", year:1993, done:false, genre:"chemistry" },
	{ title:"A Short History of Chemistry", author:"Partington", year:1937, done:false, genre:"chemistry" },
	{ title:"Drawdown", author:"Hawken", year:2017, done:false, genre:"ecology" },
	{ title:"The Uninhabitable Earth", author:"Wallace-Wells", year:2019, done:true, genre:"earth" },
	{ title:"New Views on an Old Planet", author:"Van Andel", year:1985, done:false, genre:"earth" },
	{ title:"The Norton History of the Environmental Sciences", author:"Bowler", year:1992, done:false, genre:"ecology" },
	{ title:"Silent Spring", author:"Carson", year:1962, done:true, genre:"ecology" },
	{ title:"The Sixth Extinction", author:"Kolbert", year:2014, done:false, genre:"ecology" },
	{ title:"Evolution of Physics", author:"Einstein and Infield", year:1938, done:true, genre:"physics" },
	{ title:"Relativity: the Special and the General Theory", author:"Einstein", year:1916, done:false, genre:"physics" },
	{ title:"Six Easy Pieces and Six Not-So-Easy Pieces", author:"Feynman", year:1963, done:false, genre:"physics" },
	{ title:"A Brief History of Time", author:"Hawking", year:1988, done:true, genre:"physics" },
	
	// Social Science
	{ title:"The Norton History of the Human Sciences", author:"Smith", year:1997, done:true, genre:"social" },
	// Anthropology
	{ title:"The Mind of Primitive Man", author:"Boas", year:1911, done:false, genre:"anthropology" },
	{ title:"Purity and Danger: An Analysis of Pollution and Taboo", author:"Douglas", year:1966, done:false, genre:"anthropology" },
	{ title:"Elementary Forms of Religious Life", author:"Durkheim", year:1912, done:false, genre:"anthropology" },
	{ title:"Interpretation of Cultures", author:"Geertz", year:1973, done:false, genre:"anthropology" },
	{ title:"Myth and Meaning", author:"Levi-Strauss", year:1978, done:false, genre:"anthropology" },
	{ title:"Tristes Tropiques", author:"Levi-Strauss", year:1955, done:true, genre:"anthropology" },
	{ title:"The Gift", author:"Mauss", year:1925, done:false, genre:"anthropology" },
	{ title:"Magic, Science and Religion", author:"Tambiah", year:1990, done:false, genre:"anthropology" },
	// Gender, sex and family
	{ title:"Woman, Race and Class", author:"Davis", year:1981, done:false, genre:"gender" },
	{ title:"The Second Sex", author:"de Beauvoir", year:1949, done:false, genre:"gender" },
	{ title:"Hunger", author:"Gay", year:2017, done:true, genre:"gender" },
	{ title:"Stone Butch Blues", author:"Feinberg", year:1993, done:false, genre:"gender" },
	{ title:"The Feminine Mystique", author:"Friedan", year:1963, done:false, genre:"gender" },
	{ title:"Feminism is for Everybody", author:"hooks", year:2000, done:true, genre:"gender" },
	{ title:"Families We Choose: Lesbians, Groups, Kinship", author:"Weston", year:1991, done:false, genre:"gender" },
	// Economics
	{ title:"The Division of Labor", author:"Durkheim", year:1893, done:false, genre:"economics" },
	{ title:"The Communist Manifesto", author:"Marx and Engels", year:1848, done:false, genre:"economics" },
	{ title:"The Wealth of Nations", author:"Smith", year:1776, done:false, genre:"economics" },
	{ title:"The Protestant Ethic and the Spirit of Capitalism", author:"Weber", year:1905, done:false, genre:"economics" },
	// Language and Linguistics
	{ title:"The Language Instinct", author:"Pinker", year:1994, done:true, genre:"language" },
	// Political Science
	{ title:"The Origins of Totalitarianism", author:"Arendt", year:1951, done:false, genre:"political" },
	{ title:"End of History and the Last Man", author:"Fukuyama", year:1992, done:false, genre:"political" },
	{ title:"Democracy in America", author:"De Toqueville", year:1835, done:true, genre:"political" },
	{ title:"Leviathan", author:"Hobbes", year:1651, done:false, genre:"political" },
	{ title:"The Social Contract", author:"Rousseau", year:1762, done:false, genre:"political" },
	// Psychology
	{ title:"The Social Animal", author:"Aronson", year:1972, done:false, genre:"psychology" },
	{ title:"Pioneers of Psychology", author:"Fancher", year:1979, done:false, genre:"psychology" },
	{ title:"Principles of Psychology", author:"James", year:1890, done:false, genre:"psychology" },
	{ title:"The Varieties of Religious Experience", author:"James", year:1902, done:true, genre:"psychology" },
	{ title:"Learning, Memory and Conceptual Processes", author:"Kintsch", year:1970, done:false, genre:"psychology" },
	// Race and Ethnicity
	{ title:"The New Jim Crow: Mass Incarceration in the Age of Colorblindness", author:"Alexander", year:2010, done:true, genre:"race" },
	{ title:"Between the World and Me", author:"Coates", year:2015, done:false, genre:"race" },
	{ title:"White Fragility", author:"DiAngelo", year:2018, done:false, genre:"race" },
	{ title:"Ghosts in the Schoolyard", author:"Ewing", year:2018, done:false, genre:"race" },
	{ title:"The Making of Asian America", author:"Lee", year:2015, done:true, genre:"race" },
	{ title:"Politics of the Veil", author:"Scott", year:2007, done:false, genre:"race" },
	// Sociology and Social Class
	{ title:"Imagined Communities", author:"Anderson", year:1983, done:false, genre:"sociology" },
	{ title:"Modernity at Large", author:"Appadorei", year:1996, done:false, genre:"sociology" },
	{ title:"The Social Construction of Reality", author:"Berger and Luckmann", year:1966, done:false, genre:"sociology" },
	{ title:"Suicide", author:"Durkheim", year:1897, done:false, genre:"sociology" },
	{ title:"Discipline and Punish", author:"Foucault", year:1975, done:false, genre:"sociology" },
	{ title:"Pedagogy of the Oppressed", author:"Freire", year:1968, done:true, genre:"sociology" },
	{ title:"The True Believer", author:"Hoffer", year:1951, done:false, genre:"sociology" },
	{ title:"The Sociological Imagination", author:"Mills", year:1959, done:false, genre:"sociology" },
	{ title:"Scarcity", author:"Mullainathan and Shafir", year:2013, done:false, genre:"sociology" },
	{ title:"Culture and Imperialism", author:"Said", year:1993, done:false, genre:"sociology" },
	
	// Other books of personal interest
	{ title:"Plant-Based Sports Nutrition", author:"Larson-Meyer and Ruscigno", year:2019, done:true, genre:"personal" },
	{ title:"Training Essentials for Ultrarunning", author:"Koop", year:2016, done:true, genre:"personal" },
	{ title:"Hal Koerner's Field Guide to Ultrarunning", author:"Koerner", year:2014, done:true, genre:"personal" },
	{ title:"Born to Run", author:"McDougall", year:2009, done:true, genre:"personal" },
	{ title:"Finding Ultra", author:"Roll", year:2012, done:true, genre:"personal" },
	{ title:"Eat and Run", author:"Jurek", year:2012, done:true, genre:"personal" },
	{ title:"Why Only Us: Language and Evolution", author:"Burwick and Chomsky", year:2017, done:true, genre:"personal" },
];