// Source of the array of films used to create the film list
var films = [
	// ANIMATED	
	{ title:"Snow White and the Seven Dwarfs", director:"Cottrell, Hand, and Jackson", year:1937, done:true, genre:"animated", rank:{afi:34}},
	{ title:"Toy Story", director:"Lasseter", year:1995, done:true, genre:"animated", rank:{afi:99}},
	
	// DOCUMENTARY
	{ title:"Sans Soleil", director:"Marker", year:1982, done:false, genre:"documentary", },
	
	// SILENT
	{ title:"Sunrise: A Song of Two Humans", director:"Murnau", year:1927, done:false, genre:"silent", rank:{afi:82, ssc:5, ssd:22}},
	{ title:"Passion of Joan of Arc, The", director:"Dreyer", year:1928, done:false, genre:"silent", rank:{ssc:9, ssd:37}},
	{ title:"Man with a Movie Camera", director:"Vertov", year:1929, done:false, genre:"silent", rank:{ssc:8, ssd:48}},
	{ title:"Battleship Potemkin", director:"Eisenstein", year:1925, done:false, genre:"silent", rank:{ssc:11}},
	{ title:"General, The", director:"Bruckman and Keaton", year:1926, done:false, genre:"silent", rank:{afi:18, ssc:34}},
	{ title:"Metropolis", director:"Lang", year:1927, done:false, genre:"silent", rank:{ssc:35}},
	{ title:"Sherlock Jr", director:"Keaton", year:1924, done:false, genre:"silent", },
	{ title:"Greed", director:"Stroheim", year:1924, done:false, genre:"silent", },
	{ title:"Chien Andalou, Un", director:"Buñuel", year:1928, done:false, genre:"silent", },
	{ title:"Intolerance", director:"Griffith", year:1916, done:false, genre:"silent", rank:{afi:49}},
	{ title:"Gold Rush, The", director:"Chaplin", year:1925, done:false, genre:"silent", rank:{afi:58}},
	
	// GOLDEN (1930-1949)
	{ title:"Citizen Kane", director:"Welles", year:1941, done:true, genre:"golden",rank:{afi:1, ssc:2, ssd:2} },
	{ title:"Rules of the Game, The", director:"Renoir", year:1939, done:false, genre:"golden", rank:{ssc:4}},
	{ title:"L'Atalante", director:"Vigo", year:1934, done:false, genre:"golden", rank:{ssc:12, ssd:22}},
	{ title:"Late Spring", director:"Ozu", year:1949, done:false, genre:"golden", rank:{ssc:15}},
	{ title:"Bicycle Thieves", director:"De Sica", year:1948, done:false, genre:"golden", rank:{ssc:33, ssd:10}},
	{ title:"M", director:"Lang", year:1931, done:false, genre:"golden", },
	{ title:"Modern Times", director:"Chaplin", year:1936, done:false, genre:"golden", rank:{afi:78, ssd:22}},
	{ title:"Third Man, The", director:"Reed", year:1949, done:false, genre:"golden", },
	{ title:"Enfants du Paradis, Les", director:"Carné", year:1945, done:false, genre:"golden", },
	{ title:"Grande Illusion, La", director:"Renoir", year:1937, done:false, genre:"golden", },
	{ title:"Magnificent Ambersons, The", director:"Welles", year:1942, done:false, genre:"golden", },
	{ title:"Casablanca", director:"Curtiz", year:1942, done:true, genre:"golden", rank:{afi:1} },
	{ title:"Partie de campagne", director:"Renoir", year:1936, done:false, genre:"golden", },
	{ title:"Matter of Life and Death, A", director:"Powell and Pressburger", year:1946, done:false, genre:"golden", },
	{ title:"Life and Death of Colonel Blimp, The", director:"Powell and Pressburger", year:1943, done:false, genre:"golden", },
	{ title:"Règle du Jeu, La", director:"Renoir", year:1939, done:false, genre:"golden", rank:{ssd:22}},
	{ title:"City Lights", director:"Chaplin", year:1931, done:false, genre:"golden", rank:{afi:11, ssc:50, ssd:30}},
	{ title:"Zero de Conduite", director:"Vigo", year:1933, done:false, genre:"golden", },
	{ title:"Duck Soup", director:"McCarey", year:1933, done:true, genre:"golden", rank:{afi:60}},
	{ title:"Gone with the Wind", director:"Fleming", year:1939, done:true, genre:"golden",rank:{afi:6} },
	{ title:"Wizard of Oz, The", director:"Fleming", year:1939, done:true, genre:"golden", rank:{afi:10}},
	{ title:"Mr. Smith Goes to Washington", director:"Capra", year:1939, done:true, genre:"golden", rank:{afi:26}},
	{ title:"It's a Wonderful Life", director:"Capra", year:1946, done:true, genre:"golden", rank:{afi:20}},
	{ title:"Best Years of Our Lives, The", director:"Wyler", year:1946, done:false, genre:"golden", rank:{afi:37}},
	{ title:"Grapes of Wrath, The", director:"Ford", year:1940, done:false, genre:"golden", rank:{afi:23}},
	{ title:"Double Indemnity", director:"Wilder", year:1944, done:true, genre:"golden", rank:{afi:29}},
	{ title:"It Happened One Night", director:"Capra", year:1934, done:false, genre:"golden", rank:{afi:46}},
	{ title:"Maltese Falcon, The", director:"Huston", year:1941, done:true, genre:"golden", rank:{afi:31}},
	{ title:"Treasure of the Sierra Madre, The", director:"Huston", year:1948, done:true, genre:"golden", rank:{afi:38}},
	{ title:"King Kong", director:"Cooper and Schoedsack", year:1933, done:false, genre:"golden", },
	{ title:"Philadelphia Story, The", director:"Cukor", year:1940, done:false, genre:"golden", rank:{afi:44}},
	{ title:"Sullivan's Travels", director:"Sturges", year:1941, done:false, genre:"golden", rank:{afi:61}},
	{ title:"Night at the Opera, A", director:"Wood", year:1935, done:false, genre:"golden", rank:{afi:85}},
	{ title:"Bringing Up Baby", director:"Hawks", year:1938, done:true, genre:"golden", rank:{afi:88}},
	{ title:"Swing Time", director:"Stevens", year:1936, done:false, genre:"golden", rank:{afi:90}},
	{ title:"Yankee Doodle Dandy", director:"Curtiz", year:1942, done:false, genre:"golden", rank:{afi:98}},
	
	//NEW HOLLYWOOD (1950-1969)
	{ title:"Vertigo", director:"Hitchcock", year:1958, done:true, genre:"newholly", rank:{afi:9, ssc:1, ssd:7}},
	{ title:"Tokyo Story", director:"Ozu", year:1953, done:false, genre:"newholly", rank:{ssc:3, ssd:1}},
	{ title:"All About Eve", director:"Mankiewicz", year:1950, done:true, genre:"newholly", rank:{afi:28}},
	{ title:"Streetcar Named Desire, A", director:"Kazan", year:1951, done:true, genre:"newholly", rank:{afi:47}},
	{ title:"Searchers, The", director:"Ford", year:1956, done:false, genre:"newholly", rank:{afi:12, ssc:7, ssd:48} },
	{ title:"Seven Samurai", director:"Kurosawa", year:1954, done:false, genre:"newholly", rank:{ssc:17, ssd:17}},
	{ title:"Ben-Hur", director:"Wyler", year:1959, done:false, genre:"newholly", rank:{afi:100}},
	{ title:"Singin' in the Rain", director:"Kelly and Donen", year:1952, done:true, genre:"newholly", rank:{afi:5, ssc:20}},
	{ title:"Ordet", director:"Dreyer", year:1955, done:false, genre:"newholly", rank:{ssc:24, ssd:19}},
	{ title:"Rashomon", director:"Kurosawa", year:1950, done:false, genre:"newholly", rank:{ssc:26, ssd:18}},
	{ title:"High Noon", director:"Zinnemann", year:1952, done:false, genre:"newholly", rank:{afi:27}},
	{ title:"400 Blows, The", director:"Truffaut", year:1959, done:false, genre:"newholly", rank:{ssc:39, ssd:13}},
	{ title:"Journey to Italy", director:"Rossellini", year:1954, done:false, genre:"newholly", rank:{ssc:41}},
	{ title:"Pather Panchali", director:"Ray", year:1955, done:false, genre:"newholly", rank:{ssc:42, ssd:48}},
	{ title:"Some Like It Hot", director:"Wilder", year:1959, done:false, genre:"newholly", rank:{afi:22, ssc:42, ssd:37}},
	{ title:"North By Northwest", director:"Hitchcock", year:1959, done:true, genre:"newholly", rank:{afi:55}},
	{ title:"Rear Window", director:"Hitchcock", year:1964, done:true, genre:"newholly", rank:{afi:48, ssd:48}},
	{ title:"Touch of Evil", director:"Welles", year:1954, done:false, genre:"newholly", rank:{ssd:26}},
	{ title:"Shane", director:"Stevens", year:1953, done:false, genre:"newholly", rank:{afi:45}},
	{ title:"Sansho Dayu", director:"Mizoguchi", year:1954, done:false, genre:"newholly", },
	{ title:"Wild Strawberries", director:"Bergman", year:1957, done:false, genre:"newholly", },
	{ title:"Olvidados, Los", director:"Buñuel", year:1950, done:false, genre:"newholly", },
	{ title:"Imitation of Life", director:"Stahl", year:1959, done:false, genre:"newholly", },
	{ title:"Earrings of Madame de..., The", director:"Ophüls", year:1953, done:false, genre:"newholly", },
	{ title:"Seventh Seal, The", director:"Bergman", year:1957, done:false, genre:"newholly", },
	{ title:"Sunset Blvd.", director:"Wilder", year:1950, done:true, genre:"newholly", rank:{afi:16}},
	{ title:"Night of the Hunter, The", director:"Laughton", year:1955, done:false, genre:"newholly", rank:{ssd:26}},
	{ title:"Pickpocket", director:"Bresson", year:1959, done:false, genre:"newholly", rank:{ssd:48}},
	{ title:"Rio Bravo", director:"Hawks", year:1959, done:false, genre:"newholly", },
	{ title:"Man Escaped, A", director:"Bresson", year:1958, done:false, genre:"newholly", rank:{ssd:37}},
	{ title:"2001: A Space Odyssey", director:"Kubrick", year:1968, done:true, genre:"newholly", rank:{afi:15, ssc:6, ssd:2}},
	{ title:"8 1/2", director:"Fellini", year:1968, done:false, genre:"newholly", rank:{ssc:10, ssd:4}},
	{ title:"Breathless", director:"Godard", year:1960, done:false, genre:"newholly", rank:{ssc:13, ssd:11}},
	{ title:"Au Hazard Balthazar", director:"Bresson", year:1966, done:false, genre:"newholly", rank:{ssc:16, ssd:21}},
	{ title:"Persona", director:"Bergman", year:1966, done:false, genre:"newholly", rank:{ssc:17, ssd:13}},
	{ title:"L'Avventura", director:"Antonioni", year:1960, done:false, genre:"newholly", rank:{ssc:21, ssd:30}},
	{ title:"Mépris, Le", director:"Godard", year:1963, done:false, genre:"newholly", rank:{ssc:21, ssd:44}},
	{ title:"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", director:"Kubrick", year:1964, done:true, genre:"newholly", rank:{afi:39}},
	{ title:"Sound of Music, The", director:"Wise", year:1965, done:true, genre:"newholly", rank:{afi:40}},
	{ title:"Andrei Rublev", director:"Tarkovsky", year:1966, done:false, genre:"newholly", rank:{ssc:26, ssd:13}},
	{ title:"Psycho", director:"Hitchcock", year:1960, done:true, genre:"newholly", rank:{afi:14, ssc:35, ssd:48}},
	{ title:"Dolce Vita, La", director:"Fellini", year:1960, done:false, genre:"newholly", rank:{ssc:39, ssd:37}},
	{ title:"Gertrud", director:"Dreyer", year:1964, done:false, genre:"newholly", rank:{ssc:42}},
	{ title:"Pierrot le Fou", director:"Godard", year:1965, done:false, genre:"newholly", rank:{ssc:42}},
	{ title:"Playtime", director:"Tati", year:1967, done:false, genre:"newholly", rank:{ssc:42, ssd:37}},
	{ title:"Bonnie and Clyde", director:"Penn", year:1967, done:true, genre:"newholly",rank:{afi:42} },
	{ title:"Battle of Algiers, The", director:"Pontecorvo", year:1966, done:false, genre:"newholly", rank:{ssc:48, ssd:26}},
	{ title:"Jetée, La", director:"Marker", year:1962, done:false, genre:"newholly", rank:{ssc:50}},
	{ title:"Leopard, The", director:"Visconti", year:1963, done:false, genre:"newholly", },
	{ title:"L'eclisse", director:"Antonioni", year:1962, done:false, genre:"newholly", rank:{ssd:48}},
	{ title:"To Kill a Mockingbird", director:"Mulligan", year:1962, done:false, genre:"newholly", rank:{afi:25}},
	{ title:"Once Upon a Time in the West", director:"Leone", year:1968, done:false, genre:"newholly", rank:{ssd:44}},
	{ title:"Lawrence of Arabia", director:"Lean", year:1962, done:true, genre:"", rank:{afi:7, ssd:48}},
	{ title:"Colour of Pomegranates, The", director:"Parajanov", year:1968, done:false, genre:"newholly", },
	{ title:"Wild Bunch, The", director:"Peckinpah", year:1969, done:false, genre:"newholly", rank:{afi:79}},
	{ title:"Midnight Cowboy", director:"Schlesinger", year:1969, done:true, genre:"newholly", rank:{afi:43}},
	{ title:"Strada, La", director:"Fellini", year:1954, done:false, genre:"newholly", rank:{ssd:26}},
	{ title:"On The Waterfront", director:"Kazan", year:1954, done:true, genre:"newholly", rank:{afi:19}},
	{ title:"Bridge on the River Kwai, The", director:"Lean", year:1957, done:true, genre:"newholly", rank:{afi:36}},
	{ title:"Gospel According to St. Matthew, The", director:"Pasolini", year:1964, done:false, genre:"newholly", rank:{ssd:30}},
	{ title:"Viridiana", director:"Buñuel", year:1961, done:false, genre:"newholly", rank:{ssd:37}},
	{ title:"Apartment, The", director:"Wilder", year:1960, done:false, genre:"newholly", rank:{afi:80, ssd:44}},
	{ title:"Hour of the Wolf", director:"Bergman", year:1968, done:false, genre:"newholly", rank:{ssd:44}},
	{ title:"Blow Up", director:"Antonioni", year:1966, done:false, genre:"newholly", },
	{ title:"The Good, the Bad and the Ugly", director:"Leone", year:1966, done:true, genre:"newholly", },
	{ title:"Ugetsu Monogatari", director:"Mizoguchi", year:1953, done:false, genre:"newholly", rank:{ssc:50}},
	{ title:"Kes", director:"Loach", year:1969, done:false, genre:"newholly", },
	{ title:"I am Cuba", director:"Kalatozov", year:1964, done:false, genre:"newholly", },
	{ title:"Last Year At Marienbad", director:"Resnais", year:1961, done:false, genre:"newholly", },
	{ title:"Samouraï, Le", director:"Melville", year:1967, done:false, genre:"newholly", },
	{ title:"Graduate, The", director:"Nichols", year:1967, done:true, genre:"newholly", rank:{afi:17}},
	{ title:"West Side Story", director:"Robbins and Wise", year:1961, done:true, genre:"newholly", rank:{afi:51}},
	{ title:"African Queen, The", director:"Huston", year:1951, done:true, genre:"newholly", rank:{afi:65}},
	{ title:"Who's Afraid of Virginia Woolf?", director:"Nichols", year:1966, done:false, genre:"newholly", rank:{afi:67}},
	{ title:"Butch Cassidy and the Sundance Kid", director:"Hill", year:1969, done:true, genre:"newholly", rank:{afi:73}},
	{ title:"12 Angry Men", director:"Lumet", year:1957, done:true, genre:"newholly", rank:{afi:87}},
	{ title:"In the Heat of the Night", director:"Jewison", year:1967, done:false, genre:"newholly", rank:{afi:75}},
	{ title:"Spartacus", director:"Kubrick", year:1960, done:false, genre:"newholly", rank:{afi:81}},
	{ title:"Easy Rider", director:"Hopper", year:1969, done:false, genre:"newholly", rank:{afi:84}},
	
	//BLOCKBUSTER (1970-1989)
	{ title:"Apocalypse Now", director:"Kubrick", year:1979, done:true, genre:"blockbuster", rank:{afi:30, ssc:14, ssd:6}},
	{ title:"American Graffiti", director:"Lucas and Norton", year:1973, done:false, genre:"blockbuster", rank:{afi:62}},
	{ title:"Raiders of the Lost Ark", director:"Spielberg", year:1981, done:true, genre:"blockbuster", rank:{afi:66}},
	{ title:"Cabaret", director:"Fosse", year:1972, done:false, genre:"blockbuster", rank:{afi:63}},
	{ title:"Mirror", director:"Tarkovsky", year:1975, done:false, genre:"blockbuster", rank:{ssc:19, ssd:9}},
	{ title:"Network", director:"Lumet", year:1976, done:true, genre:"blockbuster", rank:{afi:64}},
	{ title:"Godfather, The", director:"Coppola", year:1972, done:true, genre:"blockbuster", rank:{afi:2, ssc:21, ssd:7} },
	{ title:"Raging Bull", director:"Scorsese", year:1980, done:false, genre:"blockbuster", rank:{afi:4, ssd:12}},
	{ title:"Sophie's Choice", director:"Pakula", year:1982, done:false, genre:"blockbuster", rank:{afi:91}},
	{ title:"Killing of a Chinese Bookie, The", director:"Cassavetes", year:1976, done:false, genre:"blockbuster", },
	{ title:"Don't Look Now", director:"Roeg", year:1973, done:false, genre:"blockbuster", },
	{ title:"Husbands", director:"Cassavetes", year:1970, done:false, genre:"blockbuster", },
	{ title:"Salò, or the 120 Days of Sodom", director:"Pasolini", year:1975, done:false, genre:"blockbuster", },
	{ title:"Jaws", director:"Spielberg", year:1975, done:true, genre:"blockbuster", rank:{afi:56}},
	{ title:"Opening Night", director:"Cassavetes", year:1977, done:false, genre:"blockbuster", },
	{ title:"Deer Hunter, The", director:"Cimino", year:1977, done:false, genre:"blockbuster", rank:{afi:53}},
	{ title:"Platoon", director:"Stone", year:1986, done:false, genre:"blockbuster", rank:{afi:86}},
	{ title:"Annie Hall", director:"Allen", year:1977, done:true, genre:"blockbuster", rank:{afi:35}},
	{ title:"Star Wars", director:"Lucas", year:1977, done:true, genre:"blockbuster", rank:{afi:13} },
	{ title:"L'argent", director:"Bresson", year:1983, done:false, genre:"blockbuster", },
	{ title:"Shining, The", director:"Kubrick", year:1980, done:true, genre:"blockbuster", },
	{ title:"Badlands", director:"Malick", year:1973, done:false, genre:"blockbuster", },
	{ title:"Conformist, The", director:"Bertolucci", year:1970, done:false, genre:"blockbuster", },
	{ title:"Woman Under the Influence, A", director:"Cassavetes", year:1974, done:false, genre:"blockbuster", },
	{ title:"One Flew Over the Cuckoo's Nest", director:"Forman", year:1975, done:true, genre:"blockbuster", rank:{afi:33, ssd:48}},
	{ title:"Come and See", director:"Klimov", year:1985, done:false, genre:"blockbuster", rank:{ssd:30}},
	{ title:"Amarcord", director:"Fellini", year:1972, done:false, genre:"blockbuster", rank:{ssd:30}},
	{ title:"Touki Bouki", director:"Mambéty", year:1973, done:false, genre:"blockbuster", },
	{ title:"Fear Eats the Soul", director:"Fassbinder", year:1974, done:false, genre:"blockbuster", },
	{ title:"Aguirre, Wrath of God", director:"Herzog", year:1972, done:false, genre:"blockbuster", },
	{ title:"Spirit of the Beehive, The", director:"Erice", year:1973, done:false, genre:"blockbuster", },
	{ title:"Fanny and Alexander", director:"Bergman", year:1982, done:false, genre:"blockbuster", rank:{ssd:16}},
	{ title:"French Connection, The", director:"Friedkin", year:1971, done:false, genre:"blockbuster", rank:{afi:93}},
	{ title:"Nashville", director:"Altman", year:1975, done:false, genre:"blockbuster", rank:{afi:59}},
	{ title:"Chinatown", director:"Polanski", year:1974, done:true, genre:"blockbuster", rank:{afi:21}},
	{ title:"Barry Lyndon", director:"Kubrick", year:1975, done:false, genre:"blockbuster", rank:{ssd:19}},
	{ title:"Maman et la Putain, La", director:"Eustache", year:1973, done:false, genre:"blockbuster", },
	{ title:"Blade Runner", director:"Scott", year:1982, done:true, genre:"blockbuster", rank:{afi:97}},
	{ title:"Blue Velvet", director:"Lynch", year:1986, done:false, genre:"blockbuster", },
	{ title:"E.T.: The Extra-Terrestrial", director:"Spielberg", year:1982, done:true, genre:"blockbuster", rank:{afi:24}},
	{ title:"Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles", director:"Akerman", year:1975, done:false, genre:"blockbuster", rank:{ssc:35}},
	{ title:"Stalker", director:"Tarkovsky", year:1979, done:false, genre:"blockbuster", rank:{ssc:29, ssd:30}},
	{ title:"Shoah", director:"Lanzmann", year:1985, done:false, genre:"blockbuster", rank:{ssc:29, ssd:48}},
	{ title:"Godfather Part II, The", director:"Coppola", year:1974, done:true, genre:"blockbuster", rank:{afi:32, ssc:31, ssd:30}},
	{ title:"Taxi Driver", director:"Scorsese", year:1976, done:true, genre:"blockbuster", rank:{afi:52, ssc:31, ssd:5}},
	{ title:"Rocky", director:"Avildsen", year:1976, done:true, genre:"blockbuster", rank:{afi:57}},
	{ title:"M*A*S*H", director:"Altman", year:1970, done:false, genre:"blockbuster", rank:{afi:54}},
	{ title:"Tootsie", director:"Pollack", year:1982, done:false, genre:"blockbuster", rank:{afi:69}},
	{ title:"Clockwork Orange, A", director:"Kubrick", year:1971, done:true, genre:"blockbuster", rank:{afi:70}},
	{ title:"All the President's Men", director:"Pakula", year:1976, done:true, genre:"blockbuster", rank:{afi:77}},
	{ title:"Last Picture Show, The", director:"Bogdanovich", year:1971, done:false, genre:"blockbuster", rank:{afi:95}},
	{ title:"Do The Right Thing", director:"Lee", year:1989, done:true, genre:"blockbuster", rank:{afi:96}},	
	
	// MODERN (1990-)
	{ title:"Unforgiven", director:"Eastwood", year:1992, done:false, genre:"modern", rank:{afi:68}},
	{ title:"Sixth Sense, The", director:"Shyamalan", year:1999, done:true, genre:"modern", rank:{afi:89}},
	{ title:"Titanic", director:"Cameron", year:1997, done:true, genre:"modern", rank:{afi:83}},
	{ title:"Silence of the Lambs", director:"Demme", year:1991, done:true, genre:"modern", rank:{afi:74}},
	{ title:"Forrest Gump", director:"Zemeckis", year:1994, done:true, genre:"modern", rank:{afi:76}},
	{ title:"Goodfellas", director:"Tarantino", year:1990, done:true, genre:"modern", rank:{afi:92, ssd:48}},
	{ title:"Saving Private Ryan", director:"Spielberg", year:1998, done:true, genre:"modern", rank:{afi:71}},
	{ title:"Pulp Fiction", director:"Tarantino", year:1994, done:true, genre:"modern", rank:{afi:94}},
	{ title:"In The Mood for Love", director:"Wong", year:2000, done:false, genre:"modern", rank:{ssc:24}},
	{ title:"Shawshank Redemption, The", director:"Darabont", year:1994, done:true, genre:"modern", rank:{afi:72}},
	{ title:"Lord of the Rings: The Fellowship of the Ring, The", director:"Jackson", year:2001, done:true, genre:"modern", rank:{afi:50}},
	{ title:"Mulholland Drive", director:"Lynch", year:2001, done:true, genre:"modern", rank:{ssc:28}},
	{ title:"Sátántangó", director:"Tarr", year:1994, done:false, genre:"modern", rank:{ssc:35}},
	{ title:"Close-Up", director:"Kiarostami", year:1990, done:false, genre:"modern", rank:{ssc:42, ssd:37}},
	{ title:"Histoire(s) du cinéma", director:"Godard", year:"1988-1998", done:false, genre:"modern", rank:{ssc:48}},
	{ title:"Beau Travail", director:"Denis", year:1998, done:false, genre:"modern", },
	{ title:"Brighter Summer Day, A", director:"Yang", year:1991, done:false, genre:"modern", },
	{ title:"Yi Yi", director:"Yang", year:2000, done:false, genre:"modern", },
	{ title:"Hidden", director:"Duffer and Duffer", year:2004, done:false, genre:"modern", },
	{ title:"There Will Be Blood", director:"Anderson", year:2007, done:false, genre:"modern", },
	{ title:"Schindler's List", director:"Spielberg", year:1993, done:true, genre:"modern", rank:{afi:8}},
];